# Generated by Django 2.1.5 on 2019-03-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcanoRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_id', models.CharField(blank=True, max_length=128)),
                ('cospace_id', models.CharField(blank=True, max_length=128)),
                ('call_id', models.CharField(blank=True, max_length=128)),
                ('call_leg_id', models.CharField(blank=True, max_length=128)),
                ('tenant_id', models.CharField(blank=True, max_length=128)),
                ('path', models.CharField(blank=True, max_length=128)),
                ('ts_start', models.DateTimeField(null=True)),
                ('ts_stop', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcanoStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.CharField(blank=True, max_length=128)),
                ('cospace_id', models.CharField(blank=True, max_length=128)),
                ('call_id', models.CharField(blank=True, max_length=128)),
                ('call_leg_id', models.CharField(blank=True, max_length=128)),
                ('tenant_id', models.CharField(blank=True, max_length=128)),
                ('stream_url', models.CharField(max_length=200)),
                ('ts_start', models.DateTimeField(null=True)),
                ('ts_stop', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='cospaceautostreamurl',
            old_name='provider_ref',
            new_name='cospace_id',
        ),
    ]
