# Generated by Django 2.1.5 on 2019-03-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0002_auto_20190321_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='acanorecording',
            name='targets',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acanostream',
            name='targets',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
