# Generated by Django 2.1.5 on 2019-03-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0004_acanorecording_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='acanorecording',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='acanostream',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
