# Generated by Django 2.2.19 on 2021-03-25 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20210325_1707'),
        ('recording', '0006_recordinguseradmin_recordinguseralias'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.CreateModel(
                name='MeetingRecording',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                    ('backend_active', models.BooleanField(default=False)),
                    ('is_separate_streaming', models.BooleanField(default=False, editable=False)),
                    ('name', models.CharField(max_length=200)),
                    ('recording_id', models.CharField(max_length=100)),
                    ('recording_id2', models.CharField(max_length=100)),
                    ('stream_url', models.CharField(max_length=200)),
                    ('is_public', models.BooleanField(default=True)),
                    ('is_live', models.BooleanField(default=True)),
                    ('ts_activated', models.DateTimeField(null=True)),
                    ('ts_deactivated', models.DateTimeField(null=True)),
                    ('embed_code', models.TextField()),
                    ('video_sources', models.TextField()),
                    ('error', models.TextField(blank=True)),
                    ('ts_callback_sent', models.DateTimeField(null=True)),
                    ('retry_count', models.SmallIntegerField(default=0)),
                    ('schedule_id', models.CharField(max_length=20)),
                    ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting')),
                    ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.VideoCenterProvider')),
                ],
                options={
                    'db_table': 'meeting_meetingrecording',
                },
            ),
        ]),
    ]
