# Generated by Django 2.1.5 on 2019-05-27 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(verbose_name='Namn')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='NumberSeriesPrefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(db_index=True, max_length=10)),
                ('suffix', models.CharField(db_index=True, max_length=10)),
                ('last_number', models.CharField(max_length=64)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefix', to='numberseries.NumberSeries')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='numberseriesprefix',
            unique_together={('series', 'prefix', 'suffix')},
        ),
        migrations.AlterUniqueTogether(
            name='numberseries',
            unique_together={('name', 'content_type', 'object_id')},
        ),
    ]
