# Generated by Django 2.2.6 on 2020-05-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numberseries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start', models.PositiveIntegerField(default=10000000)),
                ('stop', models.PositiveIntegerField(default=99999999)),
                ('next_number', models.PositiveIntegerField(default=None, blank=True, null=True)),
            ],
        ),
    ]
