# Generated by Django 2.1.4 on 2018-12-06 13:45

from django.db import migrations, models
import django.db.models.deletion
import emailbook.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254)),
                ('uid', models.TextField(blank=True)),
                ('dialstring', models.CharField(blank=True, max_length=100)),
                ('mode', models.CharField(blank=True, max_length=100)),
                ('ts_received', models.DateTimeField(auto_now_add=True)),
                ('ts_deleted', models.DateTimeField(null=True)),
                ('secret_key', models.CharField(default=emailbook.models.new_secret_key, editable=False, max_length=16, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Customer')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Meeting')),
            ],
        ),
    ]
