# Generated by Django 2.1.5 on 2019-06-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmeeting',
            name='recurrence_id',
            field=models.TextField(blank=True),
        ),
    ]
