# Generated by Django 2.2.6 on 2020-01-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailbook', '0002_emailmeeting_recurrence_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
