# Generated by Django 2.2.6 on 2021-01-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailbook', '0003_senderlock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmeeting',
            name='dialstring',
            field=models.CharField(max_length=500),
        ),
    ]
