# Generated by Django 2.2.19 on 2021-03-25 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailbook', '0004_auto_20210108_1436'),
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.AlterField(
                model_name='emailmeeting',
                name='meeting',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting'),
            ),
        ]),
    ]
