# Generated by Django 2.2.19 on 2021-03-26 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20210325_1707'),
        ('emailbook', '0005_auto_20210325_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmeeting',
            name='recurring_meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meeting.RecurringMeeting'),
        ),
    ]
