# Generated by Django 2.2.6 on 2020-03-31 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0031_auto_20200330_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Cluster')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='NameMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_match', models.CharField(blank=True, max_length=100)),
                ('suffix_match', models.CharField(blank=True, max_length=100)),
                ('match_mode', models.SmallIntegerField(choices=[(0, 'Either'), (1, 'Both')], default=0)),
                ('customer_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerMatch')),
            ],
        ),
    ]
