# Generated by Django 2.2.6 on 2020-03-31 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NameMatch',
            new_name='CustomerNameMatch',
        ),
    ]
