# Generated by Django 2.2.6 on 2020-04-01 11:11

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200331_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermatch',
            name='regexp_match',
            field=models.CharField(blank=True, max_length=100, validators=[customer.models.validate_regexp]),
        ),
        migrations.AlterField(
            model_name='customermatch',
            name='match_mode',
            field=models.SmallIntegerField(choices=[(0, 'Either'), (1, 'Both')], default=0, help_text='Regexp overrides mode'),
        ),
    ]
