# Generated by Django 2.2.6 on 2020-04-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20200401_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermatch',
            options={'ordering': ('priority',)},
        ),
        migrations.AddField(
            model_name='customermatch',
            name='priority',
            field=models.SmallIntegerField(default=10),
        ),
    ]
