# Generated by Django 2.2.6 on 2020-04-02 06:39

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20200401_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermatch',
            name='regexp_match',
            field=models.CharField(blank=True, max_length=250, validators=[customer.models.validate_regexp]),
        ),
    ]
