# Generated by Django 2.2.6 on 2020-04-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20200402_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermatch',
            name='room_count',
            field=models.IntegerField(null=True, editable=False),
        ),
    ]
