# Generated by Django 2.2.6 on 2020-04-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customermatch_room_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermatch',
            options={'ordering': ('priority', 'id')},
        ),
        migrations.RemoveField(
            model_name='customermatch',
            name='match_mode',
        ),
        migrations.AlterField(
            model_name='customermatch',
            name='room_count',
            field=models.IntegerField(editable=False, help_text='Antalet cachade rum som matchar', null=True),
        ),
    ]
