# Generated by Django 2.2.12 on 2020-05-15 14:34

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20200414_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermatch',
            name='regexp_match',
            field=models.CharField(blank=True, help_text='Används istället för prefix/suffix. Matchar från start (implicit ^)', max_length=250, validators=[customer.models.validate_regexp], verbose_name='Regexp'),
        ),
    ]
