# Generated by Django 2.2.19 on 2021-04-16 14:15

from django.db import migrations


def migrate_key(apps, schema_editor):

    Customer = apps.get_model('provider.Customer')
    CustomerKey = apps.get_model('provider.CustomerKey')
    for c in Customer.objects.all():
        if c.shared_key:
            CustomerKey.objects.get_or_create(customer=c, shared_key=c.shared_key)



class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_customermatch_require_authorization'),
        ('emailbook', '0005_auto_20210325_1653'),
    ]

    operations = [
        migrations.RunPython(migrate_key, migrations.RunPython.noop),
    ]
