# Generated by Django 2.2.6 on 2020-03-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_provision', '0005_endpointprovisiondata_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointprovisiondata',
            name='passive',
            field=models.BooleanField(default=False),
        ),
    ]
