# Generated by Django 2.2.6 on 2020-03-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_provision', '0006_endpointprovisiondata_passive'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointprovisiondata',
            name='room_controls',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
