# Generated by Django 2.2.12 on 2020-06-26 12:06

from django.db import migrations, models

import endpoint.consts


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_provision', '0007_endpointprovisiondata_room_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointprovisiondata',
            name='room_control_templates',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='endpointtask',
            name='status',
            field=models.SmallIntegerField(choices=[(-10, 'ERROR'), (-1, 'CANCELLED'), (0, 'PENDING'), (5, 'QUEUED'), (10, 'COMPLETED')], default=endpoint.consts.TASKSTATUS(0)),
        ),
    ]
