# Generated by Django 2.2.12 on 2020-06-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_provision', '0009_endpointprovisiondata_clear_room_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointprovisiondata',
            name='room_controls_delete_operation',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
