# Generated by Django 2.2.6 on 2020-09-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_provision', '0008_auto_20200527_2152'),
        ('endpoint_provision', '0010_endpointprovisiondata_room_controls_delete_operation'),
    ]

    operations = [
    ]
