# Generated by Django 2.2.6 on 2020-12-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_provision', '0011_merge_20201011_1230'),
        ('endpoint_provision', '0011_merge_20200921_1532'),
    ]

    operations = [
    ]
