# Generated by Django 2.2.18 on 2021-02-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_provision', '0012_merge_20201205_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointfirmware',
            name='is_global',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
