# Generated by Django 2.2.19 on 2021-03-16 20:25

import django.utils.timezone
import jsonfield.fields
from django.db import migrations, models

import endpoint.consts


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_provision', '0013_auto_20210218_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointprovisiondata',
            name='commands',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='endpointprovisiondata',
            name='configuration',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='endpointprovisiondata',
            name='room_control_templates',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='endpointprovisiondata',
            name='room_controls',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='endpointtemplate',
            name='manufacturer',
            field=models.SmallIntegerField(default=endpoint.consts.MANUFACTURER(10)),
        ),
        migrations.AlterField(
            model_name='endpointtemplate',
            name='settings',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='endpointtemplate',
            name='ts_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
