# Generated by Django 2.2.19 on 2021-03-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_provision', '0014_auto_20210316_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointtask',
            name='ts_last_change',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterIndexTogether(
            name='endpointtask',
            index_together={('status', 'ts_created'), ('ts_last_change', 'ts_created')},
        ),
    ]
