# Generated by Django 2.2.24 on 2021-09-02 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_provision', '0016_auto_20210330_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointtask',
            name='endpoint',
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='endpoint.Endpoint',
            ),
        ),
    ]
