# Generated by Django 2.2.24 on 2021-09-08 14:15

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_provision', '0017_auto_20210902_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointtemplate',
            name='commands',
            field=jsonfield.fields.JSONField(default=dict, null=True),
        ),
    ]
