# Generated by Django 2.2.24 on 2021-11-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_provision', '0019_auto_20211102_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointprovisiondata',
            name='ca_certificates',
            field=models.BooleanField(default=False),
        ),
    ]
