# Generated by Django 2.2.25 on 2022-01-17 17:39

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_provision', '0020_auto_20211102_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointTargetState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('values', jsonfield.fields.JSONField(null=True)),
                ('ts_last_update', models.DateTimeField(null=True)),
                (
                    'endpoint',
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='endpoint.Endpoint',
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='endpointtargetstate',
            unique_together={('endpoint', 'type')},
        ),
    ]
