# Generated by Django 2.2.27 on 2022-03-24 11:37

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_provision', '0021_add_target_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointprovisiondata',
            name='dial_info',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
