# Generated by Django 2.2.27 on 2022-03-24 14:13

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_provision', '0022_dial_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointprovisiondata',
            name='extra_properties',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
