# Generated by Django 2.2.27 on 2022-04-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_provision', '0023_extra_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointprovisiondata',
            name='room_analytics',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
