# Generated by Django 2.1.4 on 2018-12-06 13:45

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(db_index=True, max_length=100)),
                ('uri', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('cdr_tag', models.CharField(max_length=500)),
                ('is_auto', models.BooleanField(default=False)),
                ('call_id', models.CharField(db_index=True, max_length=50)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('last_synced_data', models.DateTimeField(null=True)),
                ('last_synced_members', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoSpaceMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cospace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.CoSpace')),
            ],
        ),
        migrations.CreateModel(
            name='LdapOU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='datastore.LdapOU')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datastore_tenants', to='provider.Provider')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(db_index=True, max_length=200)),
                ('email', models.CharField(db_index=True, max_length=200)),
                ('cdr_tag', models.CharField(max_length=500)),
                ('ldap_username', models.CharField(max_length=100)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('last_synced_data', models.DateTimeField(null=True)),
                ('last_synced_ldap', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ldap_ou', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datastore.LdapOU')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datastore_users', to='provider.Provider')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datastore.Tenant')),
            ],
        ),
        migrations.AddField(
            model_name='cospacemember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.User'),
        ),
        migrations.AddField(
            model_name='cospace',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datastore.User'),
        ),
        migrations.AddField(
            model_name='cospace',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_cospaces', to='datastore.User'),
        ),
        migrations.AddField(
            model_name='cospace',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datastore_cospaces', to='provider.Provider'),
        ),
        migrations.AddField(
            model_name='cospace',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datastore.Tenant'),
        ),
        migrations.AddField(
            model_name='cospace',
            name='users',
            field=models.ManyToManyField(related_name='cospaces', through='datastore.CoSpaceMember', to='datastore.User'),
        ),
    ]
