# Generated by Django 2.1.4 on 2019-01-08 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cospace',
            name='secret',
            field=models.CharField(db_index=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cospacemember',
            name='cospace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='datastore.CoSpace'),
        ),
        migrations.AlterField(
            model_name='cospacemember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='datastore.User'),
        ),
    ]
