# Generated by Django 2.1.5 on 2019-03-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0002_auto_20190108_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='cospace',
            name='stream_url',
            field=models.CharField(db_index=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
