# Generated by Django 2.1.5 on 2019-05-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0003_cospace_stream_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cospace',
            name='ts_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='cospacemember',
            name='ts_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ts_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
