# Generated by Django 2.2.6 on 2020-01-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0021_vcseprovider_customer'),
        ('datastore', '0005_user_ts_instruction_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cospace',
            name='secondary_uri',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
