# Generated by Django 2.2.6 on 2020-01-28 10:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0021_vcseprovider_customer'),
        ('datastore', '0006_auto_20200128_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='last_synced',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cospace',
            name='last_synced',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_synced',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ldap_ou',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='datastore.LdapOU'),
        ),
        migrations.CreateModel(
            name='ProviderSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_last_sync', models.DateTimeField(null=True)),
                ('cospaces_last_sync', models.DateTimeField(null=True)),
                ('tenants_last_sync', models.DateTimeField(null=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='provider.Provider')),
            ],
        ),
    ]
