# Generated by Django 2.2.6 on 2020-04-09 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0007_auto_20200128_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='cospace',
            name='passcode',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CoSpaceAccessMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='provider.Provider')),
                ('aid', models.CharField(max_length=100)),
                ('uri', models.CharField(max_length=100)),
                ('call_id', models.CharField(max_length=100)),
                ('passcode', models.CharField(max_length=100)),
                ('cospace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='datastore.CoSpace')),
            ],
        )
    ]
