# Generated by Django 2.2.6 on 2020-04-09 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0036_acanocluster'),
        ('datastore', '0008_auto_20200409_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datastore_pexip_emails', to='provider.Provider')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('uuid', models.CharField(blank=True, max_length=100)),
                ('last_synced', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datastore_pexip_themes', to='provider.Provider')),
            ],
        ),
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('uuid', models.CharField(max_length=100)),
                ('sync_tag', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datastore.Email')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datastore_pexip_end_users', to='provider.Provider')),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200)),
                ('allow_guests', models.BooleanField(default=True)),
                ('guest_pin', models.CharField(max_length=200)),
                ('host_pin', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=500)),
                ('sync_tag', models.CharField(max_length=500)),
                ('scheduled_id', models.IntegerField(null=True)),
                ('service_type', models.CharField(max_length=100)),
                ('ts_created', models.DateTimeField(auto_now_add=True)),
                ('last_synced', models.DateTimeField(auto_now_add=True)),
                ('last_synced_data', models.DateTimeField(null=True)),
                ('last_synced_members', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datastore.Email')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datastore_pexip_conferences', to='provider.Provider')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datastore.Tenant')),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datastore.Theme')),
            ],
            options={
                'unique_together': {('provider', 'cid')},
            },
        ),
        migrations.CreateModel(
            name='ConferenceAutoParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('remote_display_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(auto_now_add=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Conference')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datastore_pexip_auto_participants', to='provider.Provider')),
            ],
            options={
                'unique_together': {('provider', 'pid')},
            },
        ),
        migrations.CreateModel(
            name='ConferenceAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(auto_now_add=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Conference')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datastore_pexip_conference_aliases', to='provider.Provider')),
            ],
            options={
                'unique_together': {('provider', 'aid')},
            },
        ),
    ]
