# Generated by Django 2.2.6 on 2020-04-09 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0036_acanocluster'),
        ('datastore', '0009_conference_conferencealias_conferenceautoparticipant_email_enduser_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencealias',
            name='alias',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='conferencealias',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='datastore.Conference'),
        ),
        migrations.AlterField(
            model_name='conferenceautoparticipant',
            name='alias',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='enduser',
            unique_together={('provider', 'uid')},
        ),
    ]
