# Generated by Django 2.2.6 on 2020-04-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0010_auto_20200409_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferenceautoparticipant',
            name='conference',
        ),
    ]
