# Generated by Django 2.2.6 on 2020-04-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0011_auto_20200409_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='automatic_participants',
            field=models.ManyToManyField(to='datastore.ConferenceAutoParticipant'),
        ),
    ]
