# Generated by Django 2.2.6 on 2020-04-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0012_auto_20200409_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='avatar_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enduser',
            name='display_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enduser',
            name='first_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enduser',
            name='last_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conference',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='conference',
            name='last_synced_data',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='last_synced_members',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='sync_tag',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='conference',
            name='tag',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='conferencealias',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='conferenceautoparticipant',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='sync_tag',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='uuid',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
