# Generated by Django 2.2.6 on 2020-04-09 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0013_auto_20200409_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enduser',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datastore.Tenant'),
        ),
    ]
