# Generated by Django 2.2.6 on 2020-04-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0036_acanocluster'),
        ('datastore', '0014_auto_20200409_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='tid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='theme',
            unique_together={('provider', 'tid')},
        ),
    ]
