# Generated by Django 2.2.6 on 2020-04-09 20:26
from collections import Counter

from django.db import migrations


def remove_duplicates(apps, schema_editor):

    Tenant = apps.get_model('datastore', 'Tenant')

    tenants = Tenant.objects.all()
    counts = Counter(tenants.values_list('tid', 'provider'))

    duplicates = [t for t, count in counts.items() if count > 1]

    for tid, provider in duplicates:
        for obj in Tenant.objects.filter(tid=tid, provider=provider).order_by('id')[1:]:
            obj.delete()


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('provider', '0036_acanocluster'),
        ('datastore', '0015_auto_20200409_2203'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='tenant',
            unique_together={('tid', 'provider')},
        ),
    ]
