# Generated by Django 2.2.6 on 2020-04-11 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customermatch_room_count'),
        ('datastore', '0016_auto_20200409_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='match',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.CustomerMatch'),
        ),
    ]
