# Generated by Django 2.2.6 on 2020-04-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0017_conference_match'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(fields=['name', 'last_synced', 'provider'], name='datastore_c_name_94a766_idx'),
        ),
    ]
