# Generated by Django 2.2.6 on 2020-04-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0018_auto_20200417_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencealias',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
