# Generated by Django 2.2.6 on 2020-04-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0019_conferencealias_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='cid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='conferencealias',
            name='aid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='conferenceautoparticipant',
            name='pid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='tid',
            field=models.IntegerField(null=True),
        ),
    ]
