# Generated by Django 2.2.6 on 2020-04-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0020_auto_20200423_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='host_pin',
            new_name='pin',
        ),
        migrations.AlterField(
            model_name='enduser',
            name='uid',
            field=models.IntegerField(null=True),
        ),
    ]
