# Generated by Django 2.2.12 on 2020-05-15 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20200515_1634'),
        ('datastore', '0023_auto_20200508_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='match',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.CustomerMatch'),
        ),
    ]
