# Generated by Django 2.2.12 on 2020-05-15 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0024_enduser_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='last_synced',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='conferencealias',
            name='last_synced',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='conferenceautoparticipant',
            name='last_synced',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='last_synced',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='theme',
            name='last_synced',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
