# Generated by Django 2.2.12 on 2020-05-15 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0025_auto_20200515_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='ts_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
