# Generated by Django 2.2.12 on 2020-06-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0026_enduser_ts_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='conference',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
