# Generated by Django 2.2.6 on 2020-10-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0027_auto_20200617_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='call_id',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
