# Generated by Django 2.2.6 on 2020-12-04 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0027_auto_20200617_2018'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cospacemember',
            unique_together={('user', 'cospace')},
        ),
    ]
