# Generated by Django 2.2.6 on 2020-12-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0028_auto_20201204_1303'),
        ('datastore', '0028_auto_20201014_1454'),
    ]

    operations = [
    ]
