# Generated by Django 2.2.17 on 2020-12-11 14:42
from collections import Counter

from django.db import migrations


def remove_duplicates(apps, schema_editor):

    CoSpace = apps.get_model('datastore', 'CoSpace')
    User = apps.get_model('datastore', 'User')

    counter = Counter(CoSpace.objects.values_list('provider', 'cid').order_by('-is_active'))
    for key, count in counter.items():
        if count > 1:
            for c in CoSpace.objects.filter(provider=key[0], cid=key[1])[1:]:
                c.delete()

    counter = Counter(User.objects.values_list('provider', 'uid'))
    for key, count in counter.items():
        if count > 1:
            for u in User.objects.filter(provider=key[0], uid=key[1])[1:]:
                u.delete()


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('datastore', '0029_merge_20201204_1707'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='cospace',
            unique_together={('provider', 'cid')},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('provider', 'uid')},
        ),
    ]
