# Generated by Django 2.2.17 on 2020-12-16 16:37

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0030_auto_20201211_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceautoparticipant',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conferenceautoparticipant',
            name='full_data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='providersync',
            name='automatic_participants_last_sync',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='providersync',
            name='themes_last_sync',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='full_data',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='conferenceautoparticipant',
            name='alias',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='conferenceautoparticipant',
            name='remote_display_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='conferenceautoparticipant',
            name='role',
            field=models.CharField(max_length=255),
        ),
    ]
