# Generated by Django 2.2.6 on 2021-01-14 07:54

from django.db import migrations
from collections import Counter


def remove_duplicates(apps, schema_editor):

    CoSpaceAccessMethod = apps.get_model('datastore', 'CoSpaceAccessMethod')
    apps.get_model('datastore', 'User')

    counter = Counter(CoSpaceAccessMethod.objects.values_list('provider', 'aid'))
    for key, count in counter.items():
        if count > 1:
            for c in CoSpaceAccessMethod.objects.filter(provider=key[0], aid=key[1])[1:]:
                c.delete()


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('datastore', '0031_auto_20201216_1737'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='cospaceaccessmethod',
            unique_together={('provider', 'aid')},
        ),
    ]
