# Generated by Django 2.2.18 on 2021-02-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0032_auto_20210114_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='providersync',
            name='aliases_last_sync',
            field=models.DateTimeField(null=True),
        ),
    ]
