# Generated by Django 2.2.18 on 2021-02-08 08:22

import datastore.models.customer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0033_auto_20210205_1656'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conference',
            name='datastore_c_name_94a766_idx',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tid',
            field=models.CharField(db_index=True, max_length=100, validators=[datastore.models.customer.no_empty]),
        ),
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(fields=['name', 'provider'], name='datastore_c_name_9f5ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(condition=models.Q(is_active=True), fields=['is_active', 'last_synced'], name='ds_pexip_conferenance_active'),
        ),
        migrations.AddIndex(
            model_name='conferencealias',
            index=models.Index(condition=models.Q(is_active=True), fields=['is_active', 'last_synced'], name='ds_pexip_alias_active'),
        ),
        migrations.AddIndex(
            model_name='cospace',
            index=models.Index(condition=models.Q(is_active=True), fields=['is_active', 'last_synced'], name='ds_acano_cospace_active'),
        ),
        migrations.AddIndex(
            model_name='enduser',
            index=models.Index(condition=models.Q(is_active=True), fields=['is_active', 'last_synced'], name='ds_pexip_enduser_active'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(is_active=True), fields=['is_active', 'last_synced'], name='ds_acano_user_is_active'),
        ),
    ]
