# Generated by Django 2.2.18 on 2021-03-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0034_auto_20210208_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_synced_cospaces',
            field=models.DateTimeField(null=True),
        ),
    ]
