# Generated by Django 2.2.18 on 2021-03-04 13:51

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0035_user_last_synced_cospaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='attributes',
            field=jsonfield.fields.JSONField(blank=True, default='{}', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(null=True, default=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='last_synced',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
