# Generated by Django 2.2.18 on 2021-03-16 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0037_cospace_num_access_methods'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conference',
            name='ds_pexip_conferenance_active',
        ),
        migrations.RemoveIndex(
            model_name='conferencealias',
            name='ds_pexip_alias_active',
        ),
        migrations.RemoveIndex(
            model_name='cospace',
            name='ds_acano_cospace_active',
        ),
        migrations.RemoveIndex(
            model_name='enduser',
            name='ds_pexip_enduser_active',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='ds_acano_user_is_active',
        ),
        migrations.AlterField(
            model_name='conference',
            name='provider',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='datastore_pexip_conferences', to='provider.Provider'),
        ),
        migrations.AlterField(
            model_name='conferencealias',
            name='provider',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='datastore_pexip_conference_aliases', to='provider.Provider'),
        ),
        migrations.AlterField(
            model_name='conferenceautoparticipant',
            name='provider',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='datastore_pexip_auto_participants', to='provider.Provider'),
        ),
        migrations.AlterField(
            model_name='cospace',
            name='provider',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='datastore_cospaces', to='provider.Provider'),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='provider',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='datastore_pexip_end_users', to='provider.Provider'),
        ),
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='datastore_users', to='provider.Provider'),
        ),
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(condition=models.Q(is_active=True), fields=['provider', 'last_synced'], name='ds_pexip_conferenance_active'),
        ),
        migrations.AddIndex(
            model_name='conferencealias',
            index=models.Index(condition=models.Q(is_active=True), fields=['provider', 'last_synced'], name='ds_pexip_alias_active'),
        ),
        migrations.AddIndex(
            model_name='cospace',
            index=models.Index(condition=models.Q(is_active=True), fields=['provider', 'last_synced'], name='ds_acano_cospace_active'),
        ),
        migrations.AddIndex(
            model_name='cospace',
            index=models.Index(condition=models.Q(is_active=True), fields=['provider', 'last_synced_data'], name='ds_acano_cospace_data'),
        ),
        migrations.AddIndex(
            model_name='enduser',
            index=models.Index(condition=models.Q(is_active=True), fields=['provider', 'last_synced'], name='ds_pexip_enduser_active'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(is_active=True), fields=['provider', 'last_synced'], name='ds_acano_user_is_active'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(is_active=True), fields=['provider', 'last_synced_data'], name='ds_acano_user_data'),
        ),
    ]
