# Generated by Django 2.2.19 on 2021-04-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0038_auto_20210316_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='providersync',
            name='last_full_sync',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='providersync',
            name='last_incremental_sync',
            field=models.DateTimeField(null=True),
        ),
    ]
