# Generated by Django 2.2.19 on 2021-04-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0039_auto_20210407_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='cospace_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='last_count_change',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='user_count',
            field=models.IntegerField(null=True),
        ),
    ]
