# Generated by Django 2.2.19 on 2021-04-15 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organizationunit_customer'),
        ('datastore', '0040_auto_20210413_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='organization_unit',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.OrganizationUnit'),
        ),
        migrations.AddField(
            model_name='cospace',
            name='organization_unit',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.OrganizationUnit'),
        ),
        migrations.AddField(
            model_name='enduser',
            name='organization_unit',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.OrganizationUnit'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization_unit',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.OrganizationUnit'),
        ),
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(condition=models.Q(('is_active', True), ('organization_unit__isnull', False)), fields=['organization_unit'], name='ds_pexip_conferenance_org'),
        ),
        migrations.AddIndex(
            model_name='cospace',
            index=models.Index(condition=models.Q(('is_active', True), ('organization_unit__isnull', False)), fields=['organization_unit'], name='ds_acano_cospace_org_unit'),
        ),
        migrations.AddIndex(
            model_name='enduser',
            index=models.Index(condition=models.Q(('is_active', True), ('organization_unit__isnull', False)), fields=['organization_unit'], name='ds_pexip_enduser_org'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(('is_active', True), ('organization_unit__isnull', False)), fields=['organization_unit'], name='ds_acano_user_org_unit'),
        ),
    ]
