# Generated by Django 2.2.19 on 2021-05-10 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0063_delete_meeting'),
        ('datastore', '0041_auto_20210415_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='customer',
            field=models.ForeignKey(db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ds_conferences', to='provider.Customer'),
        ),
        migrations.AddField(
            model_name='cospace',
            name='customer',
            field=models.ForeignKey(db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ds_cospaces', to='provider.Customer'),
        ),
        migrations.AddField(
            model_name='enduser',
            name='customer',
            field=models.ForeignKey(db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ds_endusers', to='provider.Customer'),
        ),
        migrations.AddField(
            model_name='user',
            name='customer',
            field=models.ForeignKey(db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ds_users', to='provider.Customer'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='match',
            field=models.ForeignKey(db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.CustomerMatch'),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='match',
            field=models.ForeignKey(db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.CustomerMatch'),
        ),
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(condition=models.Q(customer__isnull=False), fields=['customer'], name='ds_pexip_conferenance_cust'),
        ),
        migrations.AddIndex(
            model_name='conference',
            index=models.Index(condition=models.Q(match__isnull=False), fields=['match'], name='ds_pexip_conferenance_match'),
        ),
        migrations.AddIndex(
            model_name='cospace',
            index=models.Index(condition=models.Q(customer__isnull=False), fields=['customer'], name='ds_acano_cospace_customer'),
        ),
        migrations.AddIndex(
            model_name='enduser',
            index=models.Index(condition=models.Q(customer__isnull=False), fields=['customer'], name='ds_pexip_enduser_customer'),
        ),
        migrations.AddIndex(
            model_name='enduser',
            index=models.Index(condition=models.Q(match__isnull=False), fields=['match'], name='ds_pexip_enduser_match'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(customer__isnull=False), fields=['customer'], name='ds_acano_user_customer'),
        ),
    ]
