# Generated by Django 2.2.27 on 2022-04-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0043_auto_20211013_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='cospaceaccessmethod',
            name='scope',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cospaceaccessmethod',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
