# Generated by Django 2.2.27 on 2022-04-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0044_add_accessmethod_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='cospaceaccessmethod',
            name='secret',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
