# Generated by Django 2.2.6 on 2020-02-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomcontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcontrol',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
