# Generated by Django 2.2.6 on 2020-03-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomcontrol', '0002_auto_20200229_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcontrolfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
