# Generated by Django 2.2.6 on 2020-03-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomcontrol', '0003_auto_20200301_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcontrolfile',
            name='orig_file_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
