# Generated by Django 2.2.6 on 2020-06-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomcontrol', '0006_auto_20200616_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcontrolfile',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
