# Generated by Django 2.2.12 on 2020-06-26 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roomcontrol', '0007_roomcontrolfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcontrol',
            name='ts_last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomcontrolfile',
            name='ts_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='roomcontrolfile',
            name='ts_last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomcontroltemplate',
            name='ts_last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
