# Generated by Django 2.2.12 on 2020-06-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomcontrol', '0009_endpointcontrolstate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EndpointControlState',
            new_name='EndpointRoomControlState',
        ),
    ]
