# Generated by Django 2.2.12 on 2020-06-26 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomcontrol', '0010_auto_20200626_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointRoomControlConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomcontrol.RoomControl')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoint.Endpoint')),
            ],
        ),
        migrations.CreateModel(
            name='EndpointRoomControlTemplateConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoint.Endpoint')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomcontrol.RoomControlTemplate')),
            ],
        ),
        migrations.DeleteModel(
            name='EndpointRoomControlState',
        ),
        migrations.AddField(
            model_name='roomcontrol',
            name='endpoints',
            field=models.ManyToManyField(blank=True, related_name='room_controls', through='roomcontrol.EndpointRoomControlConnection', to='endpoint.Endpoint'),
        ),
        migrations.AddField(
            model_name='roomcontroltemplate',
            name='endpoints',
            field=models.ManyToManyField(blank=True, related_name='room_control_templates', through='roomcontrol.EndpointRoomControlTemplateConnection', to='endpoint.Endpoint'),
        ),
    ]
