# Generated by Django 2.2.6 on 2020-07-01 12:04

import compressed_store.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roomcontrol', '0011_auto_20200626_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomControlZipExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(db_index=True, default=django.utils.timezone.localtime)),
                ('content_compressed', models.BinaryField()),
                ('extra_compressed', models.BinaryField(null=True)),
                ('checksum', models.CharField(db_index=True, max_length=128)),
                ('control', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roomcontrol.RoomControl')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roomcontrol.RoomControlTemplate')),
            ],
            options={
                'abstract': False,
            },
            bases=(compressed_store.models.CompressedContentMixin, models.Model),
        ),
    ]
