# Generated by Django 2.2.6 on 2020-07-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomcontrol', '0012_roomcontrolzipexport'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcontrol',
            name='features_call_end',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='roomcontrol',
            name='features_call_join_webex',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='roomcontrol',
            name='features_call_keypad',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='roomcontrol',
            name='features_call_mid_call_controls',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='roomcontrol',
            name='features_call_start',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='roomcontrol',
            name='features_call_videomute',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='roomcontrol',
            name='features_hide_all',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='roomcontrol',
            name='features_share_start',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='roomcontrol',
            name='features_whiteboard_start',
            field=models.BooleanField(null=True),
        ),
    ]
