# Generated by Django 2.2.6 on 2020-10-15 09:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import roomcontrol.models


class Migration(migrations.Migration):

    dependencies = [
        ('roomcontrol', '0013_auto_20200701_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomControlDownloadLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('files', models.CharField(max_length=255)),
                ('controls', models.CharField(max_length=255)),
                ('templates', models.CharField(max_length=255)),
                ('endpoints', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=255)),
                ('secret_key', models.CharField(db_index=True, default=roomcontrol.models.new_secret_key, max_length=255, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Customer')),
            ],
        ),
    ]
