# Generated by Django 2.2.6 on 2020-10-15 12:56

from django.db import migrations, models
import roomcontrol.models


class Migration(migrations.Migration):

    dependencies = [
        ('roomcontrol', '0014_roomcontroldownloadlink'),
    ]

    operations = [
            migrations.AddField(
                model_name='roomcontrolzipexport',
                name='secret_key',
                field=models.CharField(db_index=True, max_length=255, unique=True, null=True),
                ),
            migrations.AlterField(
                model_name='roomcontrolzipexport',
                name='secret_key',
                field=models.CharField(db_index=True, default=roomcontrol.models.new_secret_key,
                               max_length=255, unique=True, null=True),
                ),

            ]
