# Generated by Django 2.2.6 on 2020-01-24 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0021_vcseprovider_customer'),
        ('endpoint_data', '0001_initial'),
        ('endpoint', '0042_auto_20200123_1805'),
    ]

    run_before = [
        ('endpoint', '0043_auto_20200123_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('ts_created', models.DateTimeField(auto_now_add=True)),
                ('ts_completed', models.DateTimeField(null=True)),
                ('hash', models.CharField(max_length=128)),
                ('error', models.TextField()),
                ('file', models.FileField(upload_to='backup')),
                ('configuration', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='endpoint_data.EndpointDataContent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Customer')),
                ('endpoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='endpoint.Endpoint')),
                ('macros', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='endpoint_data.EndpointDataContent')),
                ('panels', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='endpoint_data.EndpointDataContent')),
                ('status', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='endpoint_data.EndpointDataContent')),
            ],
            options={
                'ordering': ('-ts_created',),
            },
        ),
    ]
