# Generated by Django 2.2.6 on 2020-04-17 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_backup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointbackup',
            name='configuration',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='endpoint_data.EndpointDataContent'),
        ),
        migrations.AlterField(
            model_name='endpointbackup',
            name='macros',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='endpoint_data.EndpointDataContent'),
        ),
        migrations.AlterField(
            model_name='endpointbackup',
            name='panels',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='endpoint_data.EndpointDataContent'),
        ),
        migrations.AlterField(
            model_name='endpointbackup',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='endpoint_data.EndpointDataContent'),
        ),
    ]
