# Generated by Django 2.2.6 on 2020-02-20 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryStatus',
            fields=[
                ('id', models.SmallIntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('ts_last_check', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
