# Generated by Django 2.2.6 on 2020-02-21 15:21

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_celerystatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('skip_fallback_user', 'skip_fallback_user'), ('skip_acano', 'skip_acano')], max_length=100)),
                ('value', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
