# Generated by Django 2.2.6 on 2020-04-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_globaloptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ts_last_start', models.DateField(null=True)),
                ('ts_last_end', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='globaloptions',
            name='option',
            field=models.CharField(choices=[('skip_fallback_user', 'skip_fallback_user'), ('skip_acano', 'skip_acano'), ('skip_vcs', 'skip_vcs')], max_length=100),
        ),
    ]
