# Generated by Django 2.2.19 on 2021-03-25 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendar_invite', '0002_auto_20210325_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='EWSCredentials',
            fields=[
                ('credentials_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calendar_invite.Credentials')),
                ('password', models.CharField(max_length=100)),
                ('server', models.CharField(max_length=255)),
            ],
            bases=('calendar_invite.credentials',),
        ),
    ]
