# Generated by Django 2.1.4 on 2019-01-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='clustered',
            field=models.ManyToManyField(blank=True, null=True, related_name='_provider_clustered_+', to='provider.Provider'),
        ),
    ]
