# Generated by Django 2.1.4 on 2019-01-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_provider_clustered'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_private',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='provider',
            name='clustered',
            field=models.ManyToManyField(blank=True, related_name='_provider_clustered_+', to='provider.Provider'),
        ),
    ]
