# Generated by Django 2.1.4 on 2019-02-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_auto_20190123_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcseprovider',
            name='ip',
            field=models.CharField(blank=True, max_length=100, verbose_name='IP'),
        ),
    ]
