# Generated by Django 2.1.4 on 2019-03-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_vcseprovider_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='enable_recording',
            field=models.BooleanField(default=True, verbose_name='Aktivera inspelning'),
        ),
        migrations.AddField(
            model_name='customer',
            name='enable_streaming',
            field=models.BooleanField(default=True, verbose_name='Aktivera streaming'),
        ),
    ]
