# Generated by Django 2.1.5 on 2019-03-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_auto_20190306_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='cospace',
            name='call_leg_profile',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cospace',
            name='call_profile',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
