# Generated by Django 2.1.5 on 2019-03-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_auto_20190315_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocenterprovider',
            name='recording_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='Recording-key'),
        ),
        migrations.AlterField(
            model_name='videocenterprovider',
            name='type',
            field=models.IntegerField(choices=[(0, 'Videocenter'), (10, 'Rec.VC'), (20, 'Quickchannel')], default=0),
        ),
    ]
