# Generated by Django 2.1.5 on 2019-03-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0007_auto_20190315_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocenterprovider',
            name='type',
            field=models.IntegerField(choices=[(0, 'Videocenter'), (10, 'Rec.VC'), (20, 'Quickchannel'), (30, 'CMS native recording')], default=0),
        ),
    ]
