# Generated by Django 2.1.5 on 2019-03-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0008_auto_20190321_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
