# Generated by Django 2.1.5 on 2019-04-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0010_auto_20190326_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='meetingdialoutendpoint',
            name='schedule_id',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetingrecording',
            name='schedule_id',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videocenterprovider',
            name='type',
            field=models.IntegerField(choices=[(0, 'Videocenter'), (10, 'Rec.VC'), (15, 'RTMP Streaming'), (20, 'Quickchannel'), (30, 'CMS native recording'), (40, 'Mividas streaming')], default=0),
        ),
    ]
