# Generated by Django 2.1.5 on 2019-05-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0011_auto_20190425_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrecording',
            name='stream_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
