# Generated by Django 2.1.5 on 2019-06-07 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0013_auto_20190527_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='meeting',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_bookings', to='provider.Meeting'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
