# Generated by Django 2.1.5 on 2019-09-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0014_auto_20190607_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='phone_ivr',
            field=models.CharField(blank=True, max_length=25, verbose_name='Telefonnummer för uppringning'),
        ),
    ]
