# Generated by Django 2.1.5 on 2019-06-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0014_auto_20190607_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='type',
            field=models.IntegerField(choices=[(0, 'LifeSize/Acano'), (1, 'ClearSea'), (2, 'Internal'), (3, 'Externa bokningar')]),
        ),
    ]
