# Generated by Django 2.1.5 on 2019-08-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0015_auto_20190620_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='tandbergprovider',
            name='phonebook_url',
            field=models.CharField(blank=True, default='/tms/public/external/phonebook/phonebookservice.asmx?op=%s', max_length=200, verbose_name='URL'),
        ),
    ]
