# Generated by Django 2.1.5 on 2019-09-03 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0016_tandbergprovider_phonebook_url'),
        ('provider', '0015_provider_phone_ivr'),
    ]

    operations = [
    ]
