# Generated by Django 2.2.6 on 2019-11-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0017_merge_20190903_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='logo_url',
            field=models.URLField(blank=True, help_text='För inbjudningsmeddelanden', null=True),
        ),
    ]
