# Generated by Django 2.2.6 on 2020-01-22 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0019_auto_20191223_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerkey',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='provider.Customer'),
        ),
        migrations.AlterField(
            model_name='meetingwebinar',
            name='password',
            field=models.CharField(blank=True, max_length=50, verbose_name='Moderator-lösenord'),
        ),
    ]
