# Generated by Django 2.2.6 on 2020-01-22 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0020_auto_20200122_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcseprovider',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider.Customer'),
        ),
    ]
