# Generated by Django 2.2.6 on 2020-02-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0022_auto_20200218_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('title',), 'verbose_name': 'kund', 'verbose_name_plural': 'kunder'},
        ),
        migrations.AlterModelOptions(
            name='ldapprovider',
            options={'verbose_name': 'LDAP-server', 'verbose_name_plural': 'LDAP-servrar'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'permissions': (('api_client', 'Can use API-client'),), 'verbose_name': 'mötesplattform', 'verbose_name_plural': 'mötesplattformar'},
        ),
        migrations.AlterModelOptions(
            name='seeviaprovider',
            options={'verbose_name': 'seevia-konto', 'verbose_name_plural': 'seevia-konton'},
        ),
        migrations.AlterModelOptions(
            name='tandbergprovider',
            options={'verbose_name': 'Cisco/Tandberg TMS', 'verbose_name_plural': 'Cisco/Tandberg TMS'},
        ),
        migrations.AlterModelOptions(
            name='vcseprovider',
            options={'verbose_name': 'VCS Expressway', 'verbose_name_plural': 'VCS Expressways'},
        ),
        migrations.AlterModelOptions(
            name='videocenterprovider',
            options={'verbose_name': 'recording/streaming', 'verbose_name_plural': 'recording/streaming'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='always_enable_external',
            field=models.BooleanField(default=False, verbose_name='Registrera alltid clearsea'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cospace_prefix',
            field=models.CharField(blank=True, max_length=50, verbose_name='Förifylld prefix för nya mötesrum'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='type',
            field=models.IntegerField(choices=[(0, 'MCU'), (1, 'ClearSea'), (2, 'Internal'), (3, 'Externa bokningar')]),
        ),
        migrations.AlterField(
            model_name='seeviaprovider',
            name='is_test',
            field=models.BooleanField(blank=True, default=False, editable=False, verbose_name='Använd testserver'),
        ),
        migrations.AlterField(
            model_name='vcseprovider',
            name='session_expires',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='vcseprovider',
            name='session_id',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
