# Generated by Django 2.2.6 on 2020-02-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0023_auto_20200220_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='api_host',
            field=models.CharField(blank=True, help_text='Ex. 192.168.1.1:444', max_length=100, verbose_name='Ev. separat ip/host för API-anrop'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='is_standard',
            field=models.BooleanField(default=False, editable=False, help_text='Används som standard för kunder som inte har en specifik provider angedd', verbose_name='Är fallback'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='options',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='provider',
            name='session_expires',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='session_id',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='provider',
            name='subtype',
            field=models.IntegerField(blank=True, choices=[(1, 'Acano'), (0, 'LifeSize')], null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='type',
            field=models.IntegerField(choices=[(0, 'MCU'), (1, 'ClearSea'), (2, 'Internal'), (3, 'Externa bokningar')], default=0, editable=False),
        ),
    ]
