# Generated by Django 2.2.6 on 2020-02-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0024_auto_20200222_1027'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer_customer',
        ),
        migrations.AlterModelTable(
            name='customerkey',
            table='customer_customerkey',
        ),
    ]
