# Generated by Django 2.2.6 on 2020-02-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0025_auto_20200222_1044'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meeting',
            table='meeting_meeting',
        ),
        migrations.AlterModelTable(
            name='meetingdialoutendpoint',
            table='meeting_meetingdialoutendpoint',
        ),
        migrations.AlterModelTable(
            name='meetingrecording',
            table='meeting_meetingrecording',
        ),
        migrations.AlterModelTable(
            name='meetingwebinar',
            table='meeting_meetingwebinar',
        ),
    ]
