# Generated by Django 2.2.6 on 2020-03-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0028_auto_20200325_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='max_load',
            field=models.PositiveIntegerField(blank=True, help_text='125 000 för X2, 250 000 för X3', null=True, verbose_name='Max load'),
        ),
    ]
