# Generated by Django 2.2.6 on 2020-03-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0029_auto_20200328_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerload',
            name='bandwidth_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='providerload',
            name='bandwidth_out',
            field=models.IntegerField(default=0),
        ),
    ]
