# Generated by Django 2.2.6 on 2020-03-30 15:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0030_auto_20200330_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('provider.provider',),
        ),
        migrations.CreateModel(
            name='VCSCluster',
            fields=[
                ('provider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='provider.Provider')),
            ],
            bases=('provider.cluster',),
        ),
        migrations.AddField(
            model_name='provider',
            name='cluster',
            field=models.ForeignKey(blank=True, limit_choices_to={'type__in': (4, 5, 6)}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider.Cluster'),
        ),
        migrations.AddField(
            model_name='vcseprovider',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider.Cluster'),
        ),
    ]
