# Generated by Django 2.2.6 on 2020-12-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0030_auto_20200330_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='internal_domains',
            field=models.TextField(blank=True),
        ),
    ]
