# Generated by Django 2.2.6 on 2020-03-31 11:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

import customer.models
import provider.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0031_auto_20200330_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='PexipCluster',
            fields=[
                ('provider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='provider.Provider')),
            ],
            bases=('provider.cluster',),
        ),
        migrations.AlterModelOptions(
            name='vcseprovider',
            options={'verbose_name': 'VCS', 'verbose_name_plural': 'VCSer'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='shared_key',
            field=models.CharField(blank=True, default=customer.models.new_key, max_length=40),
        ),
        migrations.AlterField(
            model_name='customer',
            name='streaming_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='provider.VideoCenterProvider', verbose_name='Separat provider enbart för streaming'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='videocenter_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='provider.VideoCenterProvider', verbose_name='Inspelning/streaming-provider'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='clustered',
            field=models.ManyToManyField(blank=True, editable=False, related_name='_provider_clustered_+', to='provider.Provider'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='internal_domains',
            field=models.CharField(blank=True, help_text='Kommaseparerade', max_length=200, verbose_name='Kopplade domäner'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='subtype',
            field=models.IntegerField(blank=True, choices=[(1, 'Acano'), (2, 'Pexip Management Node'), (3, 'Pexip Node'), (0, 'LifeSize')], null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='type',
            field=models.IntegerField(choices=[(0, 'MCU'), (1, 'ClearSea'), (2, 'Internal'), (3, 'Externa bokningar'), (4, 'Acano Cluster'), (5, 'VCS Cluster'), (6, 'Pexip Cluster')], default=0),
        ),
        migrations.AlterField(
            model_name='providerload',
            name='ts_created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='PexipSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('call_id', models.IntegerField()),
                ('guid', models.UUIDField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.PexipCluster')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider.Customer')),
            ],
        ),
    ]
