# Generated by Django 2.2.6 on 2020-03-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0032_auto_20200331_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pexip_tenant_id',
            field=models.CharField(blank=True, max_length=65, verbose_name='Pexip tenant-id', default=''),
        ),
    ]
