# Generated by Django 2.2.6 on 2020-04-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0034_auto_20200331_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcseprovider',
            name='cdr_active',
            field=models.BooleanField(default=True, help_text='Maintenance > Logging > Call Data Records = "Service only"'),
        ),
    ]
