# Generated by Django 2.2.6 on 2020-04-09 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0035_auto_20200406_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcanoCluster',
            fields=[
                ('provider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='provider.Provider')),
            ],
            bases=('provider.cluster',),
        ),
    ]
