# Generated by Django 2.2.6 on 2020-04-22 19:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0036_acanocluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pexipspace',
            name='call_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pexipspace',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
