# Generated by Django 2.2.6 on 2020-05-06 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numberseries', '0002_numberrange'),
        ('provider', '0037_auto_20200422_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_domain', models.CharField(max_length=100, blank=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Cluster')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.Customer')),
                ('scheduled_room_number_serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='numberseries.NumberRange')),
                ('static_room_number_serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='numberseries.NumberRange')),
            ],
        ),
    ]
