# Generated by Django 2.2.6 on 2020-05-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0039_auto_20200507_1041'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clustersettings',
            unique_together={('cluster', 'customer')},
        ),
    ]
