# Generated by Django 2.2.6 on 2020-05-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0040_auto_20200507_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clustersettings',
            old_name='scheduled_room_number_serie',
            new_name='scheduled_room_number_range',
        ),
        migrations.RenameField(
            model_name='clustersettings',
            old_name='static_room_number_serie',
            new_name='static_room_number_range',
        ),
    ]
