# Generated by Django 2.2.12 on 2020-05-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0041_auto_20200507_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='cospace',
            name='owner_email',
            field=models.EmailField(blank=True, editable=False, max_length=254, default=''),
        ),
    ]
