# Generated by Django 2.2.12 on 2020-05-15 14:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0042_cospace_owner_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PexipEndUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField()),
                ('guid', models.UUIDField(default=uuid.uuid4)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Provider')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider.Customer')),
            ],
        ),
    ]
