# Generated by Django 2.2.12 on 2020-06-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0043_pexipenduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pexipspace',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
