# Generated by Django 2.2.6 on 2020-06-23 20:23

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organizationunit_customer'),
        ('provider', '0043_pexipenduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pexipenduser',
            name='organization_unit',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.OrganizationUnit'),
        ),
        migrations.AddField(
            model_name='pexipspace',
            name='organization_unit',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.OrganizationUnit'),
        ),
    ]
