# Generated by Django 2.2.12 on 2020-06-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0044_auto_20200617_2019'),
        ('provider', '0044_auto_20200623_2223'),
    ]

    operations = [
    ]
