# Generated by Django 2.2.6 on 2020-10-14 12:13

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0045_merge_20200625_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='pexipcluster',
            name='system_objects_data',
            field=jsonfield.fields.JSONField(default=dict, editable=False),
        ),
    ]
