# Generated by Django 2.2.6 on 2020-12-02 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0046_auto_20200903_1430'),
        ('provider', '0031_auto_20201202_1531'),
    ]

    operations = [
    ]
