# Generated by Django 2.2.6 on 2020-12-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0047_merge_20201202_1710'),
        ('provider', '0046_pexipcluster_system_objects_data'),
    ]

    operations = [
    ]
