# Generated by Django 2.2.6 on 2021-01-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0049_auto_20201208_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustersettings',
            name='additional_domains',
            field=models.TextField(blank=True),
        ),
    ]
