# Generated by Django 2.2.17 on 2021-01-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0052_meeting_ts_unbooked'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='auto_update_statistics',
            field=models.BooleanField(null=True, blank=True, default=True),
        ),
    ]
