# Generated by Django 2.2.18 on 2021-02-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0054_auto_20210131_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='session_id',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
