# Generated by Django 2.2.18 on 2021-03-03 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0058_clustersettings_remove_expired_meeting_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='use_local_call_state',
            field=models.BooleanField(null=True, default=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='use_local_database',
            field=models.BooleanField(null=True, default=True),
        ),
    ]
