# Generated by Django 2.2.18 on 2021-03-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0059_auto_20210303_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='software_version',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='vcseprovider',
            name='software_version',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
