# Generated by Django 2.2.19 on 2021-03-25 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0061_auto_20210325_1640'),
        ('meeting', '0001_initial'),
        ('statistics', '0058_auto_20210316_2036'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.AlterField(
                model_name='clearseaaccount',
                name='meeting',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting'),
            ),
            migrations.AlterField(
                model_name='meetingdialoutendpoint',
                name='meeting',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting'),
            ),
            migrations.AlterField(
                model_name='meetingrecording',
                name='meeting',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting'),
            ),
            migrations.AlterField(
                model_name='meetingwebinar',
                name='meeting',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinars', to='meeting.Meeting'),
            ),
        ]),
    ]
