# Generated by Django 2.2.24 on 2021-10-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0065_add_dial_out_location_and_ivr_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='pexipspace',
            name='ts_auto_remove',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
