# Generated by Django 2.2.27 on 2022-02-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0067_auto_20211013_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='verify_certificate',
            field=models.BooleanField(default=False, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vcseprovider',
            name='api_host',
            field=models.CharField(max_length=100, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vcseprovider',
            name='verify_certificate',
            field=models.BooleanField(default=False, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tandbergprovider',
            name='verify_certificate',
            field=models.BooleanField(default=False, null=True),
            preserve_default=False,
        ),
    ]
