# Generated by Django 2.2.27 on 2022-03-04 14:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0068_auto_20220208_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoSpaceAccessMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cospace_id', models.CharField(max_length=64)),
                ('provider_ref', models.CharField(max_length=64)),
                ('provider_ref2', models.CharField(max_length=64)),
                ('system_id', models.CharField(max_length=100, null=True)),
                (
                    'ts_created',
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ('is_virtual', models.BooleanField(blank=True, default=False)),
                ('provider_secret', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                (
                    'provider',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='provider.Provider'
                    ),
                ),
            ],
            options={
                'unique_together': {('provider', 'cospace_id', 'system_id')},
            },
        ),
    ]
