# Generated by Django 2.2.27 on 2022-05-12 08:14
import json

from django.db import migrations


def migrate_profiles(apps, schema_editor):

    AcanoCluster = apps.get_model('provider', 'AcanoCluster')
    Provider = apps.get_model('provider', 'Provider')

    for cluster in AcanoCluster.objects.all():
        provider = Provider.objects.filter(type=0, cluster=cluster).first()

        if not provider:
            continue

        cluster_options = json.loads(cluster.options or '{}')

        provider_options = json.loads(provider.options or '{}')
        if not provider_options:
            continue

        for k, v in provider_options.items():
            if k not in cluster_options and ('profile' in k or 'call_leg' in k):
                cluster_options[k] = v

        cluster.options = json.dumps(cluster_options)
        cluster.save()


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0069_auto_20220304_1502'),
    ]

    operations = [
        migrations.RunPython(migrate_profiles, migrations.RunPython.noop),
    ]
