# Generated by Django 2.2.27 on 2022-05-23 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_provision', '0024_room_analytics'),
        ('tracelog', '0001_move_tracelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracelog',
            name='endpoint_task',
            field=models.ForeignKey(
                db_constraint=False,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='endpoint_provision.EndpointTask',
            ),
        ),
    ]
