# Generated by Django 2.1.4 on 2018-12-06 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='LdapSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_dn', models.CharField(blank=True, max_length=300, verbose_name='Synka till OU')),
                ('obj_class', models.CharField(blank=True, default='InetPerson', max_length=300, verbose_name='Class för objekt')),
                ('sync_cospaces', models.BooleanField(default=False, verbose_name='Lägg upp objekt för cospaces')),
                ('sync_address_book', models.BooleanField(default=False, verbose_name='Synka adressbok')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.Customer')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.LdapProvider')),
                ('sync_tms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.TandbergProvider')),
            ],
        ),
        migrations.CreateModel(
            name='LdapSyncState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_json', models.TextField()),
                ('ts_synced', models.DateTimeField(auto_now=True)),
                ('ldap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext_sync.LdapSync')),
            ],
        ),
        migrations.CreateModel(
            name='SeeviaSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_dir', models.CharField(blank=True, max_length=64, verbose_name='Mapp-ID')),
                ('sync_meetings', models.BooleanField(default=True, verbose_name='Synka kommande möten')),
                ('sync_users', models.BooleanField(default=False, help_text='Fungerar bara för kunder med egen tenant', verbose_name='Synka användare')),
                ('sync_minutes', models.IntegerField(default=60, verbose_name='Synka möten som startar inom x min')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Customer')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.SeeviaProvider')),
            ],
        ),
        migrations.CreateModel(
            name='SeeviaSyncState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_json', models.TextField()),
                ('ts_synced', models.DateTimeField(auto_now=True)),
                ('seevia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext_sync.SeeviaSync')),
            ],
        ),
    ]
