# Generated by Django 2.2.24 on 2021-11-30 14:02

import compressed_store.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0067_auto_20211013_2034'),
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                (
                    'ts_created',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.localtime),
                ),
                ('content_compressed', models.BinaryField()),
                ('extra_compressed', models.BinaryField(null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('scope', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=255, null=True)),
                ('path', models.CharField(max_length=255, null=True)),
                (
                    'cluster',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='provider.Cluster',
                    ),
                ),
                (
                    'customer',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='provider.Customer',
                    ),
                ),
            ],
            bases=(compressed_store.models.CompressedContentMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(
                condition=models.Q(customer__isnull=True),
                fields=['customer', 'ts_created'],
                name='audit_customer',
            ),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(
                condition=models.Q(cluster__isnull=True),
                fields=['cluster', 'ts_created'],
                name='audit_cluster',
            ),
        ),
        migrations.AlterIndexTogether(
            name='auditlog',
            index_together={('username', 'ts_created'), ('type', 'ts_created')},
        ),
    ]
