# Generated by Django 2.2.24 on 2021-12-02 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='type',
            new_name='action',
        ),
        migrations.AlterIndexTogether(
            name='auditlog',
            index_together={('username', 'ts_created')},
        ),
    ]
