# Generated by Django 2.2.24 on 2021-12-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20211202_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterIndexTogether(
            name='auditlog',
            index_together={
                ('type', 'ts_created'),
                ('action', 'ts_created'),
                ('username', 'ts_created'),
            },
        ),
    ]
