# Generated by Django 2.1.5 on 2019-08-22 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0015_auto_20190620_1105'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Namn')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='external_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='external_id_str',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=128),
        ),
        migrations.CreateModel(
            name='CMSCoSpaceSource',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='address.Source')),
                ('prefix', models.CharField(max_length=200)),
                ('auto_generated', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Provider')),
            ],
            bases=('address.source',),
        ),
        migrations.CreateModel(
            name='CMSUserSource',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='address.Source')),
                ('prefix', models.CharField(max_length=200)),
                ('last_sync', models.DateTimeField(null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Provider')),
            ],
            bases=('address.source',),
        ),
        migrations.CreateModel(
            name='ManualSource',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='address.Source')),
                ('prefix', models.CharField(max_length=200)),
            ],
            bases=('address.source',),
        ),
        migrations.AddField(
            model_name='source',
            name='address_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.AddressBook'),
        ),
        migrations.AddField(
            model_name='group',
            name='address_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.AddressBook'),
        ),
        migrations.AddField(
            model_name='group',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.Source'),
        ),
    ]
