# Generated by Django 2.1.5 on 2019-08-23 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0016_tandbergprovider_phonebook_url'),
        ('address', '0002_auto_20190822_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMSSource',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='address.Source')),
                ('prefix', models.CharField(max_length=200)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.TandbergProvider')),
            ],
            bases=('address.source',),
        ),
        migrations.AddField(
            model_name='group',
            name='external_id_str',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=128),
        ),
    ]
