# Generated by Django 2.1.5 on 2019-08-23 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20190823_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPMSource',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='address.Source')),
                ('prefix', models.CharField(max_length=200)),
            ],
            bases=('address.source',),
        ),
    ]
