# Generated by Django 2.1.5 on 2019-08-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_epmsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
