# Generated by Django 2.1.5 on 2019-08-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_auto_20190823_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmssource',
            name='provider',
        ),
        migrations.AddField(
            model_name='tmssource',
            name='mac',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tmssource',
            name='phonebook_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
