# Generated by Django 2.1.5 on 2019-08-27 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organizationunit_customer'),
        ('address', '0007_auto_20190827_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='epmsource',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.OrganizationUnit'),
        ),
        migrations.AlterField(
            model_name='source',
            name='last_sync',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='prefix',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tmssource',
            name='mac',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
