# Generated by Django 2.1.5 on 2019-08-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0008_auto_20190827_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
