# Generated by Django 2.1.5 on 2019-08-27 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0009_source_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualLinkSource',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='address.Source')),
                ('manual_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.ManualSource')),
            ],
            bases=('address.source',),
        ),
        migrations.AddField(
            model_name='group',
            name='external_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Source'),
        ),
        migrations.AlterField(
            model_name='vcssource',
            name='limit_domains',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
