# Generated by Django 2.1.5 on 2019-09-04 13:08

from django.db import migrations, models
import uuid

def set_key(apps, schema_editor):

    for a in apps.get_model('address.AddressBook').objects.all():
        if not a.secret_key:
            a.secret_key = str(uuid.uuid4().hex)
            a.save()

class Migration(migrations.Migration):

    dependencies = [
        ('address', '0010_auto_20190827_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='secret_key',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='tel',
            field=models.CharField(blank=True, max_length=100, verbose_name='Teldefon'),
        ),
        migrations.RunPython(set_key, lambda x, y: x)
    ]
