# Generated by Django 2.2.6 on 2020-01-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0012_auto_20190904_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='external_edit_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='URL för redigering'),
        ),
        migrations.AddField(
            model_name='addressbook',
            name='external_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='addressbook',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Mividas Addressbook'), (1, 'External')], default=0),
        ),
    ]
