# Generated by Django 2.2.6 on 2020-04-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0014_source_sync_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmssource',
            name='mac',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
