# Generated by Django 2.2.6 on 2020-04-21 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0015_auto_20200421_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeeviaSource',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='address.Source')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('organization_id', models.UUIDField(help_text='ID på mapp eller organisation, www.seevia.me/organizations/123456-....')),
            ],
            bases=('address.source',),
        ),
    ]
