# Generated by Django 2.2.6 on 2020-08-31 17:59

from django.db import migrations


def remove_invalid(apps, schema_editor):

    apps.get_model('address', 'TMSSource').objects.filter(mac='').delete()




class Migration(migrations.Migration):

    dependencies = [
        ('address', '0016_seeviasource'),
    ]

    operations = [
        migrations.RunPython(remove_invalid, migrations.RunPython.noop)
    ]
