# Generated by Django 2.2.6 on 2020-11-16 09:14

from django.db import migrations


def set_group_root_title(apps, schema_editor):

    Group = apps.get_model('address', 'Group')
    Group.objects.filter(parent__isnull=True, title='<Root>').update(title='')


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0018_auto_20201106_1456'),
    ]

    operations = [
        migrations.RunPython(set_group_root_title, migrations.RunPython.noop)
    ]
