# Generated by Django 2.2.6 on 2020-12-03 10:25

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0019_auto_20201116_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='epmsource',
            name='flatten',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='address.Group'),
        ),
    ]
