# Generated by Django 2.2.23 on 2021-06-16 10:07

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0020_auto_20201203_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='epmsource',
            name='ignore_hide_status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
