# Generated by Django 2.1.5 on 2019-08-13 13:22

import django.db.models.deletion
from django.db import migrations, models

import endpointproxy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0015_auto_20190620_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Namn')),
                ('ts_created', models.DateTimeField(auto_now_add=True)),
                ('ts_activated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('first_ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('last_active', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_connect', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_connect_ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('ip_match', models.TextField(blank=True)),
                ('secret_key', models.CharField(default=endpointproxy.models.new_key, max_length=256, unique=True)),
                ('ssh_key', models.TextField()),
                ('proxy_version', models.CharField(blank=True, max_length=10)),
                ('reserved_port', models.IntegerField(null=True, unique=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.Customer')),
            ],
        ),
    ]
