# Generated by Django 2.1.5 on 2019-09-06 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0017_merge_20190903_0934'),
        ('endpointproxy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProxyIpNet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_net', models.CharField(max_length=100)),
                ('customer', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='provider.Customer')),
            ],
        ),
    ]
