# Generated by Django 2.1.5 on 2019-09-13 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpointproxy', '0002_customerproxyipnet'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointProxyIPNet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_net', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='endpointproxy',
            name='ip_match',
        ),
        migrations.AddField(
            model_name='endpointproxyipnet',
            name='proxy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_nets', to='endpointproxy.EndpointProxy'),
        ),
    ]
