# Generated by Django 2.2.6 on 2020-02-08 12:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpointproxy', '0004_endpointproxy_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointProxyStatusChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_connect', models.BooleanField(default=False)),
                ('is_online', models.BooleanField()),
                ('proxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='endpointproxy.EndpointProxy')),
            ],
        ),
    ]
