# Generated by Django 2.2.12 on 2020-05-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpointproxy', '0005_endpointproxystatuschange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointproxystatuschange',
            name='is_online',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
