# Generated by Django 2.2.24 on 2021-11-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpointproxy', '0006_auto_20200527_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointproxy',
            name='internal_hostname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='endpointproxy',
            name='override_rooms_hostname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='endpointproxy',
            name='use_for_firmware',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
