# Generated by Django 2.2.6 on 2020-01-29 12:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0021_vcseprovider_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointBrandingProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Namn')),
                ('ts_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='EndpointBrandingFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, 'BACKGROUND'), (2, 'BRANDING'), (3, 'HALFWAKE_BACKGROUND'), (4, 'HALFWAKE_BRANDING')])),
                ('file', models.ImageField(upload_to='branding')),
                ('use_standard', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Customer')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoint_branding.EndpointBrandingProfile')),
            ],
            options={
                'unique_together': {('profile', 'type')},
            },
        ),
    ]
