# Generated by Django 2.1.4 on 2018-12-06 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Namn')),
                ('admin_url', models.CharField(max_length=200, verbose_name='URL till adminbackend')),
                ('portal_url', models.CharField(max_length=200, verbose_name='URL till portal')),
                ('videocenter_url', models.CharField(max_length=200, verbose_name='URL till videocenter')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BackendAdministrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('handle_calls', models.BooleanField(default=False)),
                ('handle_cospaces', models.BooleanField(default=False)),
                ('handle_stats', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=True)),
                ('delete_requested', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_users', to='adminusers.AdminOrganization')),
            ],
        ),
        migrations.CreateModel(
            name='PortalAdministrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('confirmed', models.BooleanField(default=True)),
                ('delete_requested', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_users', to='adminusers.AdminOrganization')),
            ],
        ),
        migrations.CreateModel(
            name='VideoCenterAdministrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('confirmed', models.BooleanField(default=True)),
                ('delete_requested', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videocenter_users', to='adminusers.AdminOrganization')),
            ],
        ),
    ]
