
PEXIP_HELP_TEXTS = {
    "call_type": ("Maximum media content of the call. The participant being called will not be able to escalate beyond the selected capability."),
    "called_device_type": ("The device or system to which the call is routed. The options are: Registered device or external system: routes the call to a matching registered device if it is currently registered, otherwise attempts to route the call via an external system such as a SIP proxy, Lync / Skype for Business server, H.323 gatekeeper or other gateway/ITSP. Registered devices only: routes the call to a matching registered device only (providing it is currently registered). Lync / Skype for Business meeting direct (Conference ID in dialed alias): routes the call via a Lync / Skype for Business server to a Lync / Skype for Business meeting. Note that the destination alias must be transformed into just a Lync / Skype for Business Conference ID. Lync / Skype for Business clients, or meetings via a Virtual Reception: routes the call via a Lync / Skype for Business server either to a Lync / Skype for Business client, or - for calls that have come via a Virtual Reception - to a Lync / Skype for Business meeting. For Lync / Skype for Business meetings via Virtual Reception routing, ensure that Match against full alias URI is selected and that the Destination alias regex match ends with .*. Google Meet meeting: routes the call to a Google Meet meeting. Microsoft Teams meeting: routes the call to a Microsoft Teams meeting."),
    "creation_time": ("The time at which the Call Routing Rule was created."),
    "crypto_mode": ("Controls the media encryption requirements for participants connecting to this service. Use global setting: Use the global media encryption setting (Platform > Global Settings). Required: All participants (including RTMP participants) must use media encryption. Best effort: Each participant will use media encryption if their device supports it, otherwise the connection will be unencrypted. No encryption: All H.323, SIP and MS-SIP participants must use unencrypted media. (RTMP participants will use encryption if their device supports it, otherwise the connection will be unencrypted.)"),
    "description": ("A description of the Call Routing Rule."),
    "enable": ("Determines whether or not the rule is enabled. Any disabled rules still appear in the rules list but are ignored. Use this setting to test configuration changes, or to temporarily disable specific rules."),
    "external_participant_avatar_lookup": ("Determines whether or not avatars for external participants will be retrieved using the method appropriate for the external meeting type. You can use this option to override the global configuration setting."),
    "gms_access_token": ("The access token to use when resolving Google Meet meeting codes."),
    "h323_gatekeeper": ("When calling an external system, this is the H.323 gatekeeper to use for outbound H.323 calls. Select Use DNS to try to use normal H.323 resolution procedures to route the call."),
    "id": ("The primary key."),
    "ivr_theme": ("The theme for use with this service. If no theme is selected here, files from the theme that has been selected as the default (Platform > Global settings > Default theme) will be applied."),
    "match_incoming_calls": ("Applies this rule to incoming calls that have not been routed to a Virtual Meeting Room or Virtual Reception, and should be routed via the Pexip Distributed Gateway service."),
    "match_incoming_h323": ("Select whether this rule should apply to incoming H.323 calls."),
    "match_incoming_mssip": ("Select whether this rule should apply to incoming Lync / Skype for Business (MS-SIP) calls."),
    "match_incoming_only_if_registered": ("Only apply this rule to incoming calls from devices, videoconferencing endpoints, soft clients or Infinity Connect clients that are registered to Pexip Infinity.  Note that the call must also match one of the selected protocols below. Calls placed from non-registered clients or devices, or from the Infinity Connect Web App will not be routed by this rule if it is enabled."),
    "match_incoming_sip": ("Select whether this rule should apply to incoming SIP calls."),
    "match_incoming_webrtc": ("Select whether this rule should apply to incoming calls from Infinity Connect clients (WebRTC / RTMP)."),
    "match_outgoing_calls": ("Applies this rule to outgoing calls placed from a conference service (e.g. when adding a participant to a Virtual Meeting Room) where Automatic routing has been selected."),
    "match_source_location": ("Applies the rule only if the incoming call is being handled by a Conferencing Node in the selected location or the outgoing call is being initiated from the selected location. To apply the rule regardless of the location, select Any Location."),
    "match_string": ("The regular expression that the destination alias (the alias that was dialed) is checked against to see if this rule applies to this call."),
    "match_string_full": ("This setting is for advanced use cases and will not normally be required. By default, Pexip Infinity matches against a parsed version of the destination alias, i.e. it ignores the URI scheme, any other parameters, and any host IP addresses. So, if the original alias is \"sip:alice@example.com;transport=tls\" for example, then by default the rule will match against \"alice@example.com\". Select this option to match against the full, unparsed alias instead."),
    "max_callrate_in": ("This optional field allows you to limit the bandwidth of media being received by Pexip Infinity from each individual participant dialed in via this Call Routing Rule. Range: 128 to 8192."),
    "max_callrate_out": ("This optional field allows you to limit the bandwidth of media being sent by Pexip Infinity to each individual participant dialed out from this Call Routing Rule. Range: 128 to 8192."),
    "max_pixels_per_second": ("Sets the maximum call quality for each participant."),
    "mssip_proxy": ("When calling an external system, this is the Lync / Skype for Business server to use for outbound Lync / Skype for Business (MS-SIP) calls. Select Use DNS to try to use normal Lync / Skype for Business (MS-SIP) resolution procedures to route the call. When calling a Lync / Skype for Business meeting, this is the Lync / Skype for Business server to use for the Conference ID lookup and to place the call."),
    "name": ("The name used to refer to this Call Routing Rule."),
    "outgoing_location": ("When calling an external system, this forces the outgoing call to be handled by a Conferencing Node in a specific location. When calling a Lync / Skype for Business meeting, a Conferencing Node in this location will handle the outgoing call, and - for 'Lync / Skype for Business meeting direct' targets - perform the Conference ID lookup on the Lync / Skype for Business server. Select Automatic to allow Pexip Infinity to automatically select which Conferencing Node to use."),
    "outgoing_protocol": ("When calling an external system, this is the protocol to use when placing the outbound call. Note that if the call is to a registered device, Pexip Infinity will instead use the protocol that the device used to make the registration."),
    "priority": ("The priority of this rule. Rules are checked in ascending priority order until the first matching rule is found, and it is then applied. Range: 1 to 200."),
    "replace_string": ("The regular expression string used to transform the originally dialed alias (if a match was found). Leave blank to leave the originally dialed alias unchanged."),
    "resource_uri": ("The URI that identifies this resource."),
    "sip_proxy": ("When calling an external system, this is the SIP proxy to use for outbound SIP calls. Select Use DNS to try to use normal SIP resolution procedures to route the call."),
    "stun_server": ("The STUN server to be used for outbound Lync / Skype for Business (MS-SIP) calls (where applicable)."),
    "tag": ("A unique identifier used to track usage of this Call Routing Rule."),
    "teams_proxy": ("The Teams Connector to use for the Teams meeting. If you do not specify anything, the Teams Connector associated with the outgoing location is used."),
    "treat_as_trusted": ("This indicates the target of this routing rule will treat the caller as part of the target organization for trust purposes."),
    "turn_server": ("The TURN server to be used for outbound Lync / Skype for Business (MS-SIP) calls (where applicable)."),
}

PEXIP_VERBOSE_NAMES = {
    "name": ("Name"),
    "tag": ("Service tag"),
    "description": ("Description"),
    "priority": ("Priority"),
    "match_incoming_calls": ("Incoming gateway calls"),
    "match_outgoing_calls": ("Outgoing calls from a conference"),
    "match_source_location": ("Calls being handled in location"),
    "match_incoming_only_if_registered": ("Match incoming calls from registered devices only"),
    "match_incoming_webrtc": ("Match Infinity Connect (WebRTC / RTMP)"),
    "match_incoming_sip": ("Match SIP"),
    "match_incoming_mssip": ("Match Lync / Skype for Business (MS-SIP)"),
    "match_incoming_h323": ("Match H.323"),
    "match_string_full": ("Match against full alias URI"),
    "match_string": ("Destination alias regex match"),
    "replace_string": ("Destination alias regex replace string"),
    "max_callrate_in": ("Maximum inbound call bandwidth (kbps)"),
    "max_callrate_out": ("Maximum outbound call bandwidth (kbps)"),
    "call_type": ("Call capability"),
    "max_pixels_per_second": ("Maximum call quality"),
    "crypto_mode": ("Media encryption"),
    "ivr_theme": ("Theme"),
    "called_device_type": ("Call target"),
    "outgoing_location": ("Outgoing location"),
    "outgoing_protocol": ("Protocol"),
    "h323_gatekeeper": ("H.323 gatekeeper"),
    "sip_proxy": ("SIP proxy"),
    "mssip_proxy": ("Lync / Skype for Business server"),
    "teams_proxy": ("Teams Connector"),
    "turn_server": ("TURN server"),
    "stun_server": ("STUN server"),
    "gms_access_token": ("Access token"),
    "treat_as_trusted": ("Treat as trusted"),
    "external_participant_avatar_lookup": ("External participant avatar lookup"),
    "enable": ("Enable this rule"),
}
