# Generated by Django 2.2.6 on 2020-03-27 09:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0028_auto_20200325_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPolicyState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_calls', models.PositiveIntegerField(default=0)),
                ('active_participants', models.PositiveIntegerField(default=0)),
                ('participant_status', models.SmallIntegerField(choices=[(0, 'OK'), (10, 'Soft Limit'), (20, 'Hard Limit')])),
                ('last_check', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_limit', models.PositiveIntegerField(null=True)),
                ('participant_hard_limit', models.PositiveIntegerField(null=True)),
                ('date_start', models.DateField(default=datetime.date.today)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Customer')),
            ],
            options={
                'unique_together': {('customer', 'date_start')},
            },
        ),
    ]
