# Generated by Django 2.2.6 on 2020-04-11 09:31

from django.db import migrations, models
import django.db.models.deletion
import policy.models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0036_acanocluster'),
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpolicystate',
            name='active_participants_gateway',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerpolicystate',
            name='cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.Cluster'),
        ),
        migrations.AlterField(
            model_name='customerpolicy',
            name='date_start',
            field=models.DateField(default=policy.models.default_date),
        ),
        migrations.AlterField(
            model_name='customerpolicy',
            name='participant_hard_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerpolicy',
            name='participant_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerpolicystate',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.Customer'),
        ),
    ]
