# Generated by Django 2.2.6 on 2020-04-14 14:24

from django.db import migrations, models
import policy.models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_auto_20200411_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpolicy',
            name='participant_gateway_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerpolicy',
            name='participant_normal_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerpolicy',
            name='date_start',
            field=models.DateField(default=policy.models.default_date, verbose_name='Gäller fr.o.m.'),
        ),
        migrations.AlterField(
            model_name='customerpolicy',
            name='participant_limit',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.RunSQL('UPDATE policy_customerpolicy SET participant_normal_limit=participant_limit', migrations.RunSQL.noop),
    ]
