# Generated by Django 2.2.6 on 2020-04-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0004_auto_20200416_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activecall',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='activeparticipant',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
