# Generated by Django 2.2.6 on 2020-04-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0005_auto_20200416_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeparticipant',
            name='guid',
            field=models.CharField(max_length=300),
        ),
    ]
