# Generated by Django 2.2.6 on 2020-04-23 18:22

from django.db import migrations, models
import django.db.models.deletion
import policy.models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0036_acanocluster'),
        ('policy', '0005_auto_20200416_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpolicy',
            name='hard_limit_action',
            field=models.SmallIntegerField(choices=[(-1, 'Standardvärde'), (0, 'Ignore'), (100, 'Reject')], default=-1),
        ),
        migrations.AddField(
            model_name='customerpolicy',
            name='soft_limit_action',
            field=models.SmallIntegerField(choices=[(-1, 'Standardvärde'), (0, 'Ignore'), (100, 'Reject')], default=-1),
        ),
        migrations.CreateModel(
            name='ClusterPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_limit_action', models.SmallIntegerField(choices=[(0, 'Ignore'), (100, 'Reject')], default=0)),
                ('hard_limit_action', models.SmallIntegerField(choices=[(0, 'Ignore'), (100, 'Reject')], default=0)),
                ('secret_key', models.CharField(default=policy.models.new_key, editable=False, max_length=64)),
                ('cluster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.Cluster')),
            ],
        ),
    ]
