# Generated by Django 2.2.6 on 2020-04-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0006_auto_20200423_2022'),
        ('policy', '0008_policylog'),
    ]

    operations = [
    ]
