# Generated by Django 2.2.6 on 2020-04-23 19:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0037_auto_20200422_2157'),
        ('policy', '0009_merge_20200423_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policylog',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Participant'), (2, 'Call'), (10, 'Diff')]),
        ),
        migrations.CreateModel(
            name='ExternalPolicyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('message', models.TextField()),
                ('limit', models.SmallIntegerField(choices=[(0, 'OK'), (10, 'Soft Limit'), (20, 'Hard Limit')])),
                ('action', models.SmallIntegerField(choices=[(0, 'Ignore'), (100, 'Reject')], default=0)),
                ('conference', models.CharField(max_length=300)),
                ('local_alias', models.CharField(max_length=300)),
                ('remote_alias', models.CharField(max_length=300)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.Customer')),
            ],
        ),
    ]
