# Generated by Django 2.2.6 on 2020-04-24 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0037_auto_20200422_2157'),
        ('policy', '0010_auto_20200423_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalpolicylog',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider.Cluster'),
        ),
        migrations.AddField(
            model_name='policylog',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider.Cluster'),
        ),
    ]
