# Generated by Django 2.2.6 on 2020-08-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0012_auto_20200427_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalpolicylog',
            name='needs_auth',
            field=models.BooleanField(null=True),
        ),
    ]
