# Generated by Django 2.2.6 on 2020-09-17 11:41

import customer.models
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0013_auto_20200825_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_alias_match', models.CharField(blank=True, help_text='Matchar från start (implicit ^)', max_length=500, validators=[customer.models.validate_regexp], verbose_name='Alias regexp-matchning')),
                ('remote_url', models.URLField(help_text='3 sek timeout')),
                ('settings_override', jsonfield.fields.JSONField(blank=True, default=dict, help_text='Ändra inställningar för videomöte om ett svar med "result" kommer tillbaka', verbose_name='Override för rumsinställningar')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.ClusterPolicy')),
            ],
        ),
    ]
