# Generated by Django 2.2.6 on 2020-10-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0014_auto_20200917_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalpolicylog',
            name='gateway_rule',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='externalpolicylog',
            name='conference',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
