# Generated by Django 2.2.18 on 2021-02-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0016_auto_20201014_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='policylog',
            name='source',
            field=models.SmallIntegerField(null=True),
        ),
    ]
