# Generated by Django 2.2.18 on 2021-02-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0017_policylog_source'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customerpolicystate',
            constraint=models.UniqueConstraint(fields=('cluster', 'customer'), name='unique_with_customer'),
        ),
        migrations.AddConstraint(
            model_name='customerpolicystate',
            constraint=models.UniqueConstraint(condition=models.Q(customer=None), fields=('cluster',), name='unique_without_customer'),
        ),
    ]
