# Generated by Django 2.2.24 on 2021-09-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0018_auto_20210218_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalpolicy',
            old_name='local_alias_match',
            new_name='target_alias_match',
        ),
        migrations.AddField(
            model_name='externalpolicy',
            name='priority',
            field=models.SmallIntegerField(default=5),
        ),
    ]
