# Generated by Django 2.2.6 on 2020-01-23 19:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endpoint', '0043_auto_20200123_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointRoomPresence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('presence', models.BooleanField(default=False)),
                ('endpoint', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='endpoint.Endpoint')),
            ],
        ),
        migrations.CreateModel(
            name='EndpointHeadCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.localtime)),
                ('count', models.SmallIntegerField(default=0)),
                ('endpoint', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='endpoint.Endpoint')),
            ],
        ),
    ]
