# Generated by Django 2.2.24 on 2021-12-07 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0077_auto_20211129_1229'),
        ('room_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EndpointHeadCount',
            new_name='EndpointOldHeadCount',
        ),
        migrations.RenameModel(
            old_name='EndpointRoomPresence',
            new_name='EndpointOldRoomPresence',
        ),
        migrations.AlterModelTable(
            name='endpointoldroompresence',
            table='room_analytics_endpointroompresence',
        ),
        migrations.AlterModelTable(
            name='endpointoldheadcount',
            table='room_analytics_endpointheadcount',
        ),
        migrations.CreateModel(
            name='EndpointSensorValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                (
                    'ts',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.localtime),
                ),
                ('value_type', models.SmallIntegerField()),
                ('value', models.SmallIntegerField(default=0)),
                (
                    'customer',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='provider.Customer',
                    ),
                ),
                (
                    'endpoint',
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='endpoint.Endpoint',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='EndpointHeadCount',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('room_analytics.endpointsensorvalue',),
        ),
    ]
