# Generated by Django 2.2.24 on 2021-12-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_analytics', '0002_auto_20211207_1759'),
    ]

    operations = [
        migrations.RunSQL(
            '''
        INSERT INTO room_analytics_endpointsensorvalue (ts, endpoint_id, customer_id, value_type, value)
        SELECT ts, endpoint_id, customer_id, 0 AS value_type, count AS value FROM room_analytics_endpointheadcount AS h
        INNER JOIN endpoint_endpoint AS e ON h.endpoint_id=e.id
        ''',
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            '''
        INSERT INTO room_analytics_endpointsensorvalue (ts, endpoint_id, customer_id, value_type, value)
        SELECT ts, endpoint_id, customer_id, 1 AS value_type, CAST(presence AS INTEGER) AS value FROM room_analytics_endpointroompresence AS h
        INNER JOIN endpoint_endpoint AS e ON h.endpoint_id=e.id
        ''',
            migrations.RunSQL.noop,
        ),
        migrations.AddIndex(
            model_name='endpointsensorvalue',
            index=models.Index(
                fields=['endpoint', 'value_type', 'ts'], name='room_analyt_endpoin_9c6277_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='endpointsensorvalue',
            index=models.Index(fields=['customer', 'ts'], name='room_analyt_custome_afc68d_idx'),
        ),
        migrations.CreateModel(
            name='EndpointAirQuality',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('room_analytics.endpointsensorvalue',),
        ),
        migrations.CreateModel(
            name='EndpointHumidity',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('room_analytics.endpointsensorvalue',),
        ),
        migrations.CreateModel(
            name='EndpointRoomPresence',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('room_analytics.endpointsensorvalue',),
        ),
        migrations.CreateModel(
            name='EndpointTemperature',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('room_analytics.endpointsensorvalue',),
        ),
    ]
