# Generated by Django 2.2.19 on 2021-03-25 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0062_auto_20210325_1653'),
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('recurring_rule', models.CharField(max_length=100)),
                ('recurring_exceptions', models.CharField(max_length=200)),
                ('recurring_overrides', models.CharField(max_length=200)),
                ('uid', models.TextField()),
                ('external_occasion_handling', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Customer')),
                ('first_meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meeting.Meeting')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Provider')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='recurring_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, db_index=False, related_name='occurences', to='meeting.RecurringMeeting'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(condition=models.Q(recurring_master__isnull=False), fields=['recurring_master'], name='meeting_recurring_master'),
        ),
    ]
