# Generated by Django 2.2.19 on 2021-05-10 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organizationunit_customer'),
        ('meeting', '0002_auto_20210325_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='organization_unit',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.OrganizationUnit'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(condition=models.Q(organization_unit__isnull=False), fields=['organization_unit'], name='meeting_org_unit'),
        ),
    ]
