# Generated by Django 2.2.24 on 2021-12-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_meeting_moderator_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='moderator_password',
            field=models.CharField(default='', max_length=36),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='password',
            field=models.CharField(max_length=36),
        ),
    ]
