# Generated by Django 2.2.27 on 2022-02-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_auto_20211209_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='moderator_layout',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='moderator_password',
            field=models.CharField(default='', max_length=36, null=True),
        ),
    ]
