# Generated by Django 2.2.27 on 2022-05-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0008_auto_20220209_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringmeeting',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
