# Generated by Django 2.2.24 on 2021-09-14 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0065_add_dial_out_location_and_ivr_branding'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('priority', models.SmallIntegerField(default=10)),
                ('enabled', models.BooleanField(blank=True, default=True)),
                ('type', models.CharField(editable=False, max_length=255)),
                ('on_response', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingPolicyScript',
            fields=[
                (
                    'policyscript_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='policy_script.PolicyScript',
                    ),
                ),
                ('customers', models.ManyToManyField(to='provider.Customer')),
            ],
            bases=('policy_script.policyscript',),
        ),
        migrations.CreateModel(
            name='ClusterPolicyScript',
            fields=[
                (
                    'policyscript_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='policy_script.PolicyScript',
                    ),
                ),
                ('service_type', models.CharField(editable=False, max_length=255)),
                (
                    'cluster',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='provider.Cluster'
                    ),
                ),
                ('customers', models.ManyToManyField(to='provider.Customer')),
            ],
            bases=('policy_script.policyscript',),
        ),
    ]
