# Generated by Django 2.2.24 on 2021-09-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_script', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterpolicyscript',
            name='limit_customers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingpolicyscript',
            name='limit_customers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policyscript',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clusterpolicyscript',
            name='customers',
            field=models.ManyToManyField(blank=True, to='provider.Customer'),
        ),
        migrations.AlterField(
            model_name='meetingpolicyscript',
            name='customers',
            field=models.ManyToManyField(blank=True, to='provider.Customer'),
        ),
    ]
