# Generated by Django 2.2.19 on 2021-03-25 16:12

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import provider.types


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0062_auto_20210325_1653'),
        ('calendar_invite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSGraphCredentials',
            fields=[
                ('credentials_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calendar_invite.Credentials')),
            ],
            bases=('calendar_invite.credentials', provider.types.ProviderAPICompatible),
        ),
    ]
