# Generated by Django 2.1.4 on 2018-12-06 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('type', models.IntegerField(choices=[(0, 'Outlook-meddelande'), (2, 'Flerpartsmöten (både mobila och fasta klienter)'), (5, 'Flerpartsmöten med PIN-kod'), (6, 'Inbjudan cospace'), (7, 'Inbjudan acano-klient'), (8, 'Inbjudan som moderator i webinar'), (9, 'Inbjudan till webinar')])),
                ('is_active', models.BooleanField(default=True, verbose_name='Visa i lista')),
                ('content', models.TextField(help_text='Formaterad med HTML beroende på meddelande')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('type', models.IntegerField(choices=[(0, 'Outlook-meddelande'), (2, 'Flerpartsmöten (både mobila och fasta klienter)'), (5, 'Flerpartsmöten med PIN-kod'), (6, 'Inbjudan cospace'), (7, 'Inbjudan acano-klient'), (8, 'Inbjudan som moderator i webinar'), (9, 'Inbjudan till webinar')])),
                ('content', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments')),
                ('ts_created', models.DateTimeField(auto_now_add=True)),
                ('ts_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('type', models.IntegerField(choices=[(0, 'Namn på grupp för lokaler i AD'), (1, 'Hjälptext för PIN-kod'), (2, 'Aktivera externa deltagare')])),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.Customer')),
            ],
        ),
    ]
