# Generated by Django 2.1.4 on 2019-02-08 09:32

from django.db import migrations, models
import uuid
import hashlib


def set_secret(apps, schema_editor):
    Message = apps.get_model('ui_message', 'Message')

    for m in Message.objects.all():
        m.secret_key = hashlib.md5('{}{}'.format(m.pk, m.ts_created).encode('utf-8') * 5).hexdigest()
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ui_message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='secret_key',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
        migrations.AlterField(
            model_name='defaultmessage',
            name='type',
            field=models.IntegerField(choices=[(0, 'Outlook-meddelande'), (2, 'Flerpartsmöten (både mobila och fasta klienter)'), (5, 'Flerpartsmöten med PIN-kod'), (6, 'Inbjudan cospace'), (10, 'Inbjudan användare'), (7, 'Inbjudan acano-klient'), (8, 'Inbjudan som moderator i webinar'), (9, 'Inbjudan till webinar')]),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.IntegerField(choices=[(0, 'Outlook-meddelande'), (2, 'Flerpartsmöten (både mobila och fasta klienter)'), (5, 'Flerpartsmöten med PIN-kod'), (6, 'Inbjudan cospace'), (10, 'Inbjudan användare'), (7, 'Inbjudan acano-klient'), (8, 'Inbjudan som moderator i webinar'), (9, 'Inbjudan till webinar')]),
        ),
        migrations.RunPython(set_secret),

    ]
