# Generated by Django 2.2.6 on 2020-08-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_auth', '0003_auto_20200825_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyauthorization',
            name='usage_count',
            field=models.SmallIntegerField(null=True),
        ),
    ]
