# Generated by Django 2.2.6 on 2020-08-27 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policy_auth', '0004_policyauthorization_usage_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='policywhitelist',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='policyauthorization',
            name='require_fields',
            field=jsonfield.fields.JSONField(blank=True, default=dict, help_text='Matchar fält från policy-server mot dessa. Ex: {"remote_display_name": "Test"}'),
        ),
        migrations.AlterField(
            model_name='policyauthorization',
            name='usage_count',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policyauthorization',
            name='usage_limit',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policyauthorization',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='policyauthorization',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
