# Generated by Django 2.2.6 on 2020-08-27 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy_auth', '0005_auto_20200827_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policywhitelist',
            old_name='whitelist',
            new_name='remote_list',
        ),
    ]
