# Generated by Django 2.2.6 on 2020-08-27 10:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0045_merge_20200625_1210'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policy_auth', '0006_auto_20200827_1211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PolicyWhitelist',
            new_name='PolicyAuthorizationOverride',
        ),
    ]
