# Generated by Django 2.2.24 on 2021-10-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_auth', '0008_auto_20201118_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyauthorization',
            name='external_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
