
POLICY_RULE_TEST_DATA = {
    'enable': True,
    'sync_back': False,
    'name': 'Test',
    'tag': '',
    'description': '',
    'priority': 10,
    'match_incoming_calls': True,
    'match_outgoing_calls': True,
    'match_source_location': None,
    'match_source_alias': '',
    'match_source_mode': 'AND',
    'match_incoming_only_if_registered': False,
    'match_incoming_webrtc': True,
    'match_incoming_sip': True,
    'match_incoming_mssip': True,
    'match_incoming_h323': True,
    'match_string_full': False,
    'match_string': r'(1234)@local.com',
    'replace_string': '',
    'call_type': 'auto',
    'max_callrate_in': None,
    'max_callrate_out': None,
    'max_pixels_per_second': None,
    'crypto_mode': '',
    'ivr_theme': None,
    'called_device_type': 'external',
    'outgoing_location': None,
    'outgoing_protocol': 'sip',
    'sip_proxy': None,
    'teams_proxy': None,
    'gms_access_token': None,
    'h323_gatekeeper': None,
    'mssip_proxy': None,
    'stun_server': None,
    'turn_server': None,
    'external_participant_avatar_lookup': 'default',
    'treat_as_trusted': True,

    'external_id': None,
}
