# Generated by Django 2.2.6 on 2020-01-24 07:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import compressed_store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endpoint', '0042_auto_20200123_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointDataContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('content_compressed', models.BinaryField()),
                ('extra_compressed', models.BinaryField(null=True)),
                ('content_type', models.SmallIntegerField(choices=[(0, 'configuration'), (1, 'status'), (2, 'command'), (10, 'macros'), (11, 'panels')])),
                ('hash', models.CharField(max_length=64)),
                ('endpoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='endpoint.Endpoint')),
            ],
            options={
                'abstract': False,
            },
            bases=(compressed_store.models.CompressedContentMixin, models.Model),
        ),
    ]
