# Generated by Django 2.2.6 on 2020-02-03 15:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import compressed_store.models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0045_auto_20200203_1643'),
        ('endpoint_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointDataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('content_compressed', models.BinaryField()),
                ('extra_compressed', models.BinaryField(null=True)),
                ('content_type', models.SmallIntegerField(choices=[(0, 'configuration'), (1, 'status'), (2, 'command'), (10, 'macros'), (11, 'panels')])),
                ('hash', models.CharField(max_length=64)),
                ('endpoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='endpoint.Endpoint')),
                ('parent', models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='endpoint_data.EndpointDataFile')),
            ],
            options={
                'abstract': False,
            },
            bases=(compressed_store.models.CompressedContentMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EndpointCurrentState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='endpoint_data.EndpointDataFile')),
                ('endpoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='endpoint.Endpoint')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='endpoint_data.EndpointDataFile')),
                ('valuespace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='endpoint_data.EndpointDataFile')),
            ],
        ),
    ]
