# Generated by Django 2.2.6 on 2020-02-03 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_data', '0002_endpointcurrentstate_endpointdatafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointcurrentstate',
            name='command',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='endpoint_data.EndpointDataFile'),
        ),
    ]
