# Generated by Django 2.2.6 on 2020-02-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_data', '0003_endpointcurrentstate_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointdatafile',
            name='hash_cleaned',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endpointdatacontent',
            name='content_type',
            field=models.SmallIntegerField(choices=[(0, 'configuration'), (1, 'status'), (2, 'command'), (3, 'valuespace'), (10, 'macros'), (11, 'panels')]),
        ),
        migrations.AlterField(
            model_name='endpointdatafile',
            name='content_type',
            field=models.SmallIntegerField(choices=[(0, 'configuration'), (1, 'status'), (2, 'command'), (3, 'valuespace'), (10, 'macros'), (11, 'panels')]),
        ),
    ]
