# Generated by Django 2.2.6 on 2020-02-20 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_data', '0004_auto_20200203_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointcurrentstate',
            name='endpoint',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='endpoint.Endpoint'),
        ),
    ]
