# Generated by Django 2.2.6 on 2020-02-20 12:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_data', '0005_auto_20200220_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointdatacontent',
            name='ts_created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='endpointdatafile',
            name='ts_created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.localtime),
        ),
    ]
