# Generated by Django 2.2.6 on 2020-04-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_data', '0006_auto_20200220_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointdatafile',
            name='ts_first_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='endpointdatafile',
            name='reuse_count',
            field=models.IntegerField(null=True, default=None),
        ),
    ]
