# Generated by Django 2.2.6 on 2020-04-17 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_data', '0008_auto_20200408_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointcurrentstate',
            name='command',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='endpoint_data.EndpointDataFile'),
        ),
        migrations.AlterField(
            model_name='endpointcurrentstate',
            name='configuration',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='endpoint_data.EndpointDataFile'),
        ),
        migrations.AlterField(
            model_name='endpointcurrentstate',
            name='status',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='endpoint_data.EndpointDataFile'),
        ),
        migrations.AlterField(
            model_name='endpointcurrentstate',
            name='valuespace',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='endpoint_data.EndpointDataFile'),
        ),
    ]
