# Generated by Django 2.2.18 on 2021-02-11 09:38

from django.db import migrations, models
from django.db.models import F


def update_data(apps, schema_editor):

    EndpointDataFile = apps.get_model('endpoint_data', 'EndpointDataFile')
    EndpointDataFile.objects.filter(ts_last_used__isnull=False, ts_last_used__lt=F('ts_created')).update(ts_created=F('ts_last_used'), ts_last_used=F('ts_created'))


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('endpoint_data', '0009_auto_20200417_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpointdatafile',
            old_name='ts_first_created',
            new_name='ts_last_used',
        ),
        migrations.RunPython(update_data, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='endpointdatafile',
            index=models.Index(condition=models.Q(ts_last_used__isnull=False), fields=['ts_last_used'], name='endpoint_datafile_last_used'),
        ),
    ]
