# Generated by Django 2.2.24 on 2021-11-03 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_data', '0011_auto_20210902_1138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EndpointCurrentState',
            new_name='EndpointCurrentStateOld',
        ),
        migrations.AlterModelTable(
            name='endpointcurrentstateold',
            table='endpoint_data_endpointcurrentstate',
        ),
    ]
