# Generated by Django 2.2.24 on 2021-11-03 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_data', '0012_auto_20211103_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointcurrentstateold',
            name='endpoint',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='endpoint.Endpoint',
            ),
        ),
        migrations.CreateModel(
            name='EndpointCurrentState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                (
                    'command',
                    models.ForeignKey(
                        db_index=False,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='endpoint_data.EndpointDataContent',
                    ),
                ),
                (
                    'configuration',
                    models.ForeignKey(
                        db_index=False,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='endpoint_data.EndpointDataContent',
                    ),
                ),
                (
                    'endpoint',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='files',
                        to='endpoint.Endpoint',
                    ),
                ),
                (
                    'status',
                    models.ForeignKey(
                        db_index=False,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='endpoint_data.EndpointDataContent',
                    ),
                ),
                (
                    'valuespace',
                    models.ForeignKey(
                        db_index=False,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='endpoint_data.EndpointDataContent',
                    ),
                ),
            ],
            options={
                'db_table': 'endpoint_data_endpointcurrentstate_new',
            },
        ),
    ]
