# Generated by Django 2.2.19 on 2021-03-25 16:12

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import provider.types


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0062_auto_20210325_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('tenant_id', models.CharField(max_length=255)),
                ('secret', models.CharField(max_length=255)),
                ('authorization', models.CharField(editable=False, max_length=255)),
                ('access_token', jsonfield.fields.JSONField(default=dict, editable=False)),
                ('use_app_authorization', models.BooleanField(default=False)),
                ('type', models.SmallIntegerField(default=0)),
                ('customer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='provider.Customer')),
            ],
        ),
    ]
