# Generated by Django 2.2.19 on 2021-04-16 13:38

import api_key.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0063_delete_meeting'),
        ('api_key', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAPIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('key', models.CharField(default=api_key.models.new_key, max_length=200)),
                ('limit_customers', models.ManyToManyField(blank=True, to='provider.Customer')),
            ],
        ),
    ]
