# Generated by Django 2.2.24 on 2021-12-08 22:06

import api_key.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_key', '0003_auto_20210416_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingapikey',
            name='enable_cospace_changes',
            field=models.BooleanField(default=False),
        ),
    ]
