# Generated by Django 2.2.6 on 2020-02-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debuglog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acanocdrlog',
            name='id_prefixes',
            field=models.CharField(max_length=300, verbose_name='Store first digits of leg/call ids for searching'),
        ),
    ]
