# Generated by Django 2.2.6 on 2020-02-19 19:01

import compressed_store.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0050_auto_20200219_1940'),
        ('debuglog', '0002_auto_20200203_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointCiscoProvision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('content_compressed', models.BinaryField()),
                ('extra_compressed', models.BinaryField(null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('event', models.CharField(max_length=100)),
                ('endpoint', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='endpoint.Endpoint')),
            ],
            options={
                'abstract': False,
            },
            bases=(compressed_store.models.CompressedContentMixin, models.Model),
        ),
    ]
