# Generated by Django 2.2.6 on 2020-04-02 08:42
import json

from django.db import migrations, models
from compressed_store.models import CompressedContentMixin


def set_count(apps, schema):

    PexipHistoryLog = apps.get_model('debuglog', 'PexipHistoryLog')
    for h in PexipHistoryLog.objects.all():
        try:
            data = json.loads(CompressedContentMixin._decompress(h.content_compressed))
        except Exception:
            raise
        if not isinstance(data, dict):
            continue

        h.count = len(data['objects'])
        h.save()


class Migration(migrations.Migration):

    dependencies = [
        ('debuglog', '0005_pexipeventlog_pexiphistorylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pexiphistorylog',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(set_count, migrations.RunPython.noop)
    ]
