# Generated by Django 2.2.6 on 2020-04-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debuglog', '0006_pexiphistorylog_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pexipeventlog',
            name='uuid_start',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
