# Generated by Django 2.2.6 on 2020-04-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debuglog', '0009_auto_20200403_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pexipeventlog',
            name='uuid_start',
            field=models.CharField(max_length=36),
        ),
    ]
