# Generated by Django 2.2.19 on 2021-05-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debuglog', '0010_auto_20200427_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='acanocdrlog',
            name='count',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='acanocdrlog',
            name='types',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
