# Generated by Django 2.2.24 on 2021-09-11 15:23

import compressed_store.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('debuglog', '0011_auto_20210512_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='PexipPolicyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                (
                    'ts_created',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.localtime),
                ),
                ('content_compressed', models.BinaryField()),
                ('extra_compressed', models.BinaryField(null=True)),
                ('cluster_id', models.IntegerField(null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('type', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=255)),
                ('service_tag', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
            ],
            options={
                'index_together': {('service_tag', 'ts_created')},
            },
            bases=(compressed_store.models.CompressedContentMixin, models.Model),
        ),
    ]
