# Generated by Django 2.2.24 on 2021-12-17 10:21

import compressed_store.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('debuglog', '0012_auto_20210911_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                (
                    'ts_created',
                    models.DateTimeField(db_index=True, default=django.utils.timezone.localtime),
                ),
                ('content_compressed', models.BinaryField()),
                ('extra_compressed', models.BinaryField(null=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(compressed_store.models.CompressedContentMixin, models.Model),
        ),
    ]
