# Generated by Django 2.2.27 on 2022-05-23 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debuglog', '0016_add_trace_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracelog',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='tracelog',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='tracelog',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='tracelog',
            name='provider',
        ),
        migrations.DeleteModel(
            name='ActiveTraceLog',
        ),
        migrations.DeleteModel(
            name='TraceLog',
        ),
    ]
