# Generated by Django 2.2.28 on 2022-06-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debuglog', '0017_move_tracelog'),
        ('debuglog', '0016_add_poly_log'),
    ]

    operations = []
