# Generated by Django 2.1.4 on 2018-12-06 13:45

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(db_index=True, max_length=64)),
                ('tenant', models.CharField(db_index=True, max_length=64)),
                ('cospace', models.CharField(max_length=100)),
                ('cospace_id', models.CharField(max_length=100)),
                ('ou', models.CharField(db_index=True, max_length=200)),
                ('cdr_tag', models.CharField(max_length=200)),
                ('leg_count', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('total_duration', models.IntegerField(default=0)),
                ('ts_start', models.DateTimeField(db_index=True, null=True)),
                ('ts_stop', models.DateTimeField(db_index=True, null=True)),
                ('licenses_json', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoSpaceUnitRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_ref', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DayStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('ou', models.CharField(db_index=True, max_length=200)),
                ('calls', models.IntegerField()),
                ('users', models.IntegerField()),
                ('max_users', models.IntegerField()),
                ('minutes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DomainTransform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=30)),
                ('ou', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.CharField(db_index=True, max_length=64)),
                ('guid', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('should_count_stats', models.BooleanField(default=True)),
                ('direction', models.CharField(max_length=20)),
                ('remote', models.CharField(db_index=True, max_length=200)),
                ('local', models.CharField(db_index=True, max_length=200)),
                ('target', models.CharField(db_index=True, max_length=200)),
                ('ts_start', models.DateTimeField(db_index=True, null=True)),
                ('ts_stop', models.DateTimeField(db_index=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('is_guest', models.BooleanField(default=False)),
                ('ou', models.CharField(db_index=True, max_length=200)),
                ('tx_pixels', models.IntegerField(null=True)),
                ('rx_pixels', models.IntegerField(null=True)),
                ('bandwidth', models.IntegerField(null=True)),
                ('packetloss_percent', models.SmallIntegerField(default=0)),
                ('jitter_percent', models.SmallIntegerField(default=0)),
                ('jitter', models.SmallIntegerField(default=0)),
                ('jitter_peak', models.SmallIntegerField(default=0)),
                ('contribution_percent', models.SmallIntegerField(default=0)),
                ('presentation_contribution_percent', models.SmallIntegerField(default=0)),
                ('viewer_percent', models.SmallIntegerField(default=0)),
                ('call', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='statistics.Call')),
            ],
            options={
                'ordering': ('ts_start',),
            },
        ),
        migrations.CreateModel(
            name='OrganisationUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='statistics.OrganisationUnit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='UserUnitRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_jid', models.CharField(max_length=200)),
                ('unit', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.OrganisationUnit')),
            ],
        ),
        migrations.AddField(
            model_name='leg',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.Server'),
        ),
        migrations.AddField(
            model_name='daystat',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.Server'),
        ),
        migrations.AddField(
            model_name='cospaceunitrelation',
            name='unit',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.OrganisationUnit'),
        ),
        migrations.AddField(
            model_name='call',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.Server'),
        ),
    ]
