# Generated by Django 2.1.4 on 2018-12-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cospaceunitrelation',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='organisationunit',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='userunitrelation',
            name='unit',
        ),
        migrations.DeleteModel(
            name='CoSpaceUnitRelation',
        ),
        migrations.DeleteModel(
            name='OrganisationUnit',
        ),
        migrations.DeleteModel(
            name='UserUnitRelation',
        ),
    ]
