# Generated by Django 2.1.4 on 2019-01-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0002_auto_20181206_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='high_roundtrip_percent',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='leg',
            name='contribution_percent',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='leg',
            name='jitter',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='leg',
            name='jitter_peak',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='leg',
            name='jitter_percent',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='leg',
            name='packetloss_percent',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='leg',
            name='presentation_contribution_percent',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='leg',
            name='viewer_percent',
            field=models.SmallIntegerField(null=True),
        ),
    ]
