# Generated by Django 2.1.4 on 2019-01-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0003_auto_20190109_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='protocol',
            field=models.SmallIntegerField(choices=[(0, 'SIP'), (1, 'H323'), (2, 'CMS'), (3, 'Lync')], null=True),
        ),
    ]
