# Generated by Django 2.1.4 on 2019-02-21 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0006_auto_20190116_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(db_index=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Ou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(db_index=True, max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='call',
            name='cospace_id_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statistics.CoSpace'),
        ),
        migrations.AddField(
            model_name='call',
            name='ou_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statistics.Ou'),
        ),
        migrations.AddField(
            model_name='call',
            name='tenant_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statistics.Tenant'),
        ),
        migrations.AddField(
            model_name='leg',
            name='ou_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statistics.Ou'),
        ),
        migrations.AddField(
            model_name='leg',
            name='tenant_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statistics.Tenant'),
        ),
    ]
