# Generated by Django 2.1.5 on 2019-03-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0007_auto_20190221_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leg',
            name='local',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='leg',
            name='remote',
            field=models.CharField(max_length=200),
        ),
    ]
