# Generated by Django 2.1.5 on 2019-10-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0008_auto_20190315_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(db_index=True, max_length=200, verbose_name='full target')),
                ('domain', models.CharField(db_index=True, max_length=200, verbose_name='only domain')),
            ],
        ),
        migrations.AddField(
            model_name='cospace',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
