# Generated by Django 2.1.5 on 2019-10-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0010_auto_20191010_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='only domain')),
            ],
        ),
        migrations.RemoveField(
            model_name='target',
            name='domain',
        ),
        migrations.AddField(
            model_name='target',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL, to='statistics.Domain'),
        ),
        migrations.AlterField(
            model_name='cospace',
            name='guid',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='ou',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='guid',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
