# Generated by Django 2.1.5 on 2019-10-16 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0011_auto_20191010_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidCallStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics.Server')),
                ('day', models.DateField()),
                ('unknown_destination', models.IntegerField(default=0)),
                ('other', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='invalidcallstats',
            unique_together={('server', 'day')},
        ),
    ]
