# Generated by Django 2.1.5 on 2019-10-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0012_invalidcallstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invalidcallstats',
            name='day',
            field=models.DateField(unique=True),
        ),
    ]
