# Generated by Django 2.1.5 on 2019-10-16 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0013_auto_20191016_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossibleSpamLeg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=200)),
                ('ts_start', models.DateTimeField()),
                ('data_json', models.TextField()),
                ('server', models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE, to='statistics.Server')),
            ],
        ),
    ]
