# Generated by Django 2.2.6 on 2019-10-21 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organizationunit_customer'),
        ('statistics', '0014_possiblespamleg'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='org_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.OrganizationUnit'),
        ),
        migrations.AlterField(
            model_name='invalidcallstats',
            name='day',
            field=models.DateField(),
        ),
    ]
