# Generated by Django 2.2.6 on 2019-10-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0015_auto_20191021_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='domain',
        ),
        migrations.AddField(
            model_name='target',
            name='domain',
            field=models.CharField(default='', max_length=200, verbose_name='domain'),
            preserve_default=False,
        ),
    ]
