# Generated by Django 2.2.6 on 2019-10-25 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organizationunit_customer'),
        ('statistics', '0017_auto_20191024_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='org_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.OrganizationUnit'),
        ),
    ]
