# Generated by Django 2.2.6 on 2019-10-25 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_organizationunit_customer'),
        ('statistics', '0018_call_org_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaintransform',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.OrganizationUnit'),
        ),
        migrations.AlterField(
            model_name='domaintransform',
            name='ou',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
