# Generated by Django 2.2.6 on 2020-01-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0021_server_default_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='head_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
