# Generated by Django 2.2.6 on 2020-01-17 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0039_endpoint_room_capacity'),
        ('statistics', '0022_leg_head_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='endpoint',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='endpoint.Endpoint'),
        ),
    ]
