# Generated by Django 2.2.6 on 2020-02-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0024_auto_20200122_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='combine_servers',
            field=models.ManyToManyField(blank=True, to='statistics.Server'),
        ),
        migrations.AlterField(
            model_name='server',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Cisco Meeting Server'), (1, 'Cisco VCS'), (2, 'Endpoints'), (3, 'Combine')], default=0),
        ),
    ]
