# Generated by Django 2.2.6 on 2020-02-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0024_auto_20200122_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='licenses_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
