# Generated by Django 2.2.6 on 2020-02-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0025_auto_20200224_1332'),
        ('statistics', '0025_auto_20200216_1625'),
    ]

    operations = [
    ]
