# Generated by Django 2.2.6 on 2020-02-28 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0026_merge_20200227_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='domain',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statistics.Domain'),
        ),
    ]
