# Generated by Django 2.2.6 on 2020-11-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0027_auto_20200228_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
