# Generated by Django 2.2.6 on 2020-04-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0030_auto_20200401_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='cospace_id_fk',
        ),
        migrations.RemoveField(
            model_name='call',
            name='ou_fk',
        ),
        migrations.RemoveField(
            model_name='leg',
            name='ou_fk',
        ),
        migrations.RemoveField(
            model_name='leg',
            name='target_fk',
        ),
        migrations.DeleteModel(
            name='CoSpace',
        ),
        migrations.DeleteModel(
            name='Ou',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
