# Generated by Django 2.2.6 on 2020-04-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0031_auto_20200401_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leg',
            name='guid',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
