# Generated by Django 2.2.6 on 2020-04-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0032_auto_20200401_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='license_count',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='license_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='service_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
