# Generated by Django 2.2.6 on 2020-04-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0033_auto_20200403_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='cospace',
            field=models.CharField(db_index=True, max_length=300),
        ),
    ]
