# Generated by Django 2.2.6 on 2020-04-07 08:22

from django.db import migrations
from django.conf import settings


def get_sql():
    POSTGRES_SQL = [
        ('UPDATE statistics_leg SET duration=EXTRACT(EPOCH FROM (ts_stop - ts_start)) where '
        'duration is null or duration=0 and ts_start is not null and ts_stop is not null'),
        'UPDATE statistics_leg SET should_count_stats=\'f\' WHERE ts_stop is not null and duration < 60',
    ]

    if 'postgre' in settings.DATABASES['default']['ENGINE']:
        return POSTGRES_SQL

    # OTHER
    return [
        'UPDATE statistics_leg SET should_count_stats=0 WHERE ts_stop is not null and duration < 60',
    ]


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0034_auto_20200403_2003'),
    ]

    operations = [
        migrations.RunSQL(sql=get_sql(), reverse_sql=migrations.RunSQL.noop),
    ]
