# Generated by Django 2.2.6 on 2020-04-07 11:26

from django.db import migrations, models
import statistics.models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0035_auto_20200407_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leg',
            name='ts_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='leg',
            name='ts_stop',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='secret_key',
            field=models.CharField(blank=True, db_index=True, default=statistics.models.new_key, editable=False, max_length=100),
        ),

    ]
