# Generated by Django 2.2.6 on 2020-04-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0036_auto_20200407_1326'),
    ]

    operations = [
    ]
