# Generated by Django 2.2.6 on 2020-04-07 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0037_auto_20200407_1332'),
    ]
    operations = [
        migrations.AlterField(
            model_name='call',
            name='cospace',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='call',
            name='guid',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='call',
            name='ou',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='call',
            name='server',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='statistics.Server'),
        ),
        migrations.AlterField(
            model_name='call',
            name='ts_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='ts_stop',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='leg',
            name='guid',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='leg',
            name='server',
            field=models.ForeignKey(db_index=False, related_name='legs', on_delete=django.db.models.deletion.CASCADE, to='statistics.Server'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(
                condition=models.Q(
                    ('correlator_guid__isnull', False), models.Q(_negated=True, correlator_guid='')
                ),
                fields=['correlator_guid'],
                name='correlator_guid',
            ),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(condition=models.Q(_negated=True, cospace_id=''), fields=['cospace_id'], name='cospace_id'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['ts_start', 'ts_stop'], name='statistics__ts_star_0da1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['guid', 'server'], name='statistics__guid_e1caef_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['cospace', 'ts_start', 'ts_stop'], name='statistics__cospace_41ccf9_idx'),
        ),
        migrations.AddIndex(
            model_name='leg',
            index=models.Index(fields=['ts_start', 'server', 'guid'], name='statistics__ts_star_832a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='leg',
            index=models.Index(condition=models.Q(should_count_stats=True), fields=['ts_start', 'ts_stop', 'server', 'tenant'], name='leg_server'),
        ),
    ]
