# Generated by Django 2.2.6 on 2020-04-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0038_auto_20200407_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='guid2',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
