# Generated by Django 2.2.6 on 2020-04-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0039_leg_guid2'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='cdr_event_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='history_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
