# Generated by Django 2.2.6 on 2020-04-17 09:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0040_auto_20200417_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('guid', models.CharField(max_length=300, unique=True)),
                ('first_leg_guid', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='leg',
            name='conversation',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statistics.LegConversation'),
        ),
    ]
