# Generated by Django 2.2.6 on 2020-04-17 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0042_auto_20200417_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='legconversation',
            name='server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='statistics.Server'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legconversation',
            name='guid',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterUniqueTogether(
            name='legconversation',
            unique_together={('server', 'guid')},
        ),
    ]
