# Generated by Django 2.2.6 on 2020-04-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0043_auto_20200417_1220'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='call',
            name='statistics__cospace_41ccf9_idx',
        ),
        migrations.RemoveIndex(
            model_name='leg',
            name='statistics__ts_star_832a7a_idx',
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['cospace', 'server', 'ts_start', 'ts_stop'], name='statistics__cospace_543353_idx'),
        ),
        migrations.AddIndex(
            model_name='leg',
            index=models.Index(fields=['guid', 'server'], name='statistics__guid_5cec33_idx'),
        ),
    ]
