# Generated by Django 2.2.6 on 2020-04-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0044_auto_20200418_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legconversation',
            name='guid',
            field=models.CharField(max_length=500),
        ),
    ]
