# Generated by Django 2.2.6 on 2020-04-21 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debuglog', '0009_auto_20200403_1436'),
        ('statistics', '0045_auto_20200420_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='pexip_cdr_event_logs',
            field=models.ManyToManyField(db_constraint=False, to='debuglog.PexipEventLog'),
        ),
        migrations.AddField(
            model_name='leg',
            name='pexip_history_logs',
            field=models.ManyToManyField(db_constraint=False, to='debuglog.PexipHistoryLog'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='cdr_log',
            field=models.ForeignKey(db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='debuglog.PexipEventLog'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='history_log',
            field=models.ForeignKey(db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='debuglog.PexipHistoryLog'),
        ),
    ]
