# Generated by Django 2.2.6 on 2020-08-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debuglog', '0010_auto_20200427_1801'),
        ('statistics', '0046_auto_20200421_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='cdr_log',
        ),
        migrations.RemoveField(
            model_name='call',
            name='history_log',
        ),
        migrations.RemoveField(
            model_name='leg',
            name='cdr_event_data',
        ),
        migrations.RemoveField(
            model_name='leg',
            name='cdr_log',
        ),
        migrations.RemoveField(
            model_name='leg',
            name='history_data',
        ),
        migrations.RemoveField(
            model_name='leg',
            name='history_log',
        ),
        migrations.AddField(
            model_name='call',
            name='pexip_cdr_event_logs',
            field=models.ManyToManyField(db_constraint=False, related_name='statistics_calls', to='debuglog.PexipEventLog'),
        ),
        migrations.AddField(
            model_name='call',
            name='pexip_history_logs',
            field=models.ManyToManyField(db_constraint=False, related_name='statistics_calls', to='debuglog.PexipHistoryLog'),
        ),
    ]
