# Generated by Django 2.2.6 on 2020-08-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debuglog', '0010_auto_20200427_1801'),
        ('statistics', '0047_auto_20200831_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='acano_cdr_event_logs',
            field=models.ManyToManyField(db_constraint=False, related_name='statistics_calls', to='debuglog.AcanoCDRLog'),
        ),
        migrations.AddField(
            model_name='leg',
            name='acano_cdr_event_logs',
            field=models.ManyToManyField(db_constraint=False, related_name='statistics_legs', to='debuglog.AcanoCDRLog'),
        ),
    ]
