# Generated by Django 2.2.6 on 2020-11-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0049_auto_20200831_2109'),
        ('statistics', '0028_auto_20201117_1612'),
    ]

    operations = [
    ]
