# Generated by Django 2.2.6 on 2020-12-03 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0050_merge_20201117_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leg',
            name='orig_call',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='statistics.Call'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='ou',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='leg',
            name='target',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='leg',
            name='tenant',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='leg',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AddIndex(
            model_name='leg',
            index=models.Index(fields=['target'], name='statistics__target_ac0a95_idx'),
        ),
    ]
