# Generated by Django 2.2.17 on 2020-12-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0051_auto_20201203_1657'),
    ]

    operations = [
    ]
