# Generated by Django 2.2.6 on 2021-01-14 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0052_auto_20201210_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='meeting',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, db_index=False, on_delete=django.db.models.deletion.SET_NULL, to='provider.Meeting'),
        ),
    ]
