# Generated by Django 2.2.17 on 2021-02-01 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0053_auto_20210114_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leg',
            name='orig_call',
            field=models.ForeignKey(db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='statistics.Call'),
        ),
    ]
