# Generated by Django 2.2.18 on 2021-03-03 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0054_auto_20210201_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='keep_external_participants',
            field=models.BooleanField(null=True, default=False),
        ),
    ]
