# Generated by Django 2.2.19 on 2021-03-16 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0055_auto_20210303_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leg',
            name='conversation',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='statistics.LegConversation'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='domain',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='statistics.Domain'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='endpoint',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='endpoint.Endpoint'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='orig_call',
            field=models.ForeignKey(db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='statistics.Call'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='pexip_cdr_event_logs',
            field=models.ManyToManyField(db_constraint=False, related_name='statistics_legs', to='debuglog.PexipEventLog'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='pexip_history_logs',
            field=models.ManyToManyField(db_constraint=False, related_name='statistics_legs', to='debuglog.PexipHistoryLog'),
        ),
    ]
