# Generated by Django 2.2.19 on 2021-03-16 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0056_auto_20210316_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='org_unit',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.OrganizationUnit'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='endpoint',
            field=models.ForeignKey(blank=True, db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='endpoint.Endpoint'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='org_unit',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.OrganizationUnit'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='conversation',
            field=models.ForeignKey(db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='statistics.LegConversation'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(condition=models.Q(org_unit__isnull=False), fields=['org_unit'], name='call_org_unit'),
        ),
        migrations.AddIndex(
            model_name='leg',
            index=models.Index(condition=models.Q(endpoint__isnull=False), fields=['endpoint'], name='leg_endpoint'),
        ),
        migrations.AddIndex(
            model_name='leg',
            index=models.Index(condition=models.Q(org_unit__isnull=False), fields=['org_unit'], name='org_unit'),
        ),
        migrations.AddIndex(
            model_name='leg',
            index=models.Index(condition=models.Q(conversation__isnull=False), fields=['conversation'], name='leg_conversation'),
        ),
    ]
