# Generated by Django 2.2.19 on 2021-03-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0059_leg_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='guid',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='leg',
            name='guid',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.RunSQL(
            "UPDATE statistics_call SET guid=NULL WHERE guid=''",
            "UPDATE statistics_call SET guid='' WHERE guid is null",
        ),
        migrations.RunSQL(
            "UPDATE statistics_leg SET guid=NULL WHERE guid=''",
            "UPDATE statistics_leg SET guid='' WHERE guid is null",
        ),
    ]
