# Generated by Django 2.2.24 on 2021-11-02 09:19

from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0063_call_ts_finalized'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                (
                    'server',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='statistics.Server'
                    ),
                ),
            ],
            options={
                'unique_together': {('type', 'server')},
            },
        ),
        migrations.CreateModel(
            name='ActiveCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('guid', models.CharField(max_length=500)),
                ('node', models.CharField(max_length=500)),
                ('ts_last_update', models.DateTimeField(default=now)),
                (
                    'server',
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='statistics.Server',
                    ),
                ),
            ],
            options={
                'unique_together': {('guid', 'node', 'server')},
            },
        ),
    ]
