# Generated by Django 2.2.24 on 2021-11-05 13:04
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0064_activecall_statisticslock'),
    ]

    operations = (
        [
            migrations.RunSQL(
                '''
        UPDATE statistics_call SET ts_stop=ts_start WHERE ts_start < NOW() - INTERVAL '4 hours' AND ts_stop IS NULL
        ''',
                migrations.RunSQL.noop,
            ),
            migrations.RunSQL(
                '''
        UPDATE statistics_leg SET ts_stop=ts_start, should_count_stats='f' where ts_start < NOW() - INTERVAL '4 hours' AND ts_stop IS NULL
        ''',
                migrations.RunSQL.noop,
            ),
        ]
        if 'postgres' in settings.DATABASES['default']['ENGINE']
        else []
    )
