# Generated by Django 2.1.5 on 2019-04-12 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0010_auto_20190326_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=100, verbose_name='DNS-namn')),
                ('sip', models.CharField(blank=True, max_length=100, verbose_name='SIP')),
                ('h323', models.CharField(blank=True, max_length=100, verbose_name='H323')),
                ('h323_e164', models.CharField(blank=True, max_length=100, verbose_name='H323 E.164')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-nummer')),
                ('username', models.CharField(blank=True, max_length=50, verbose_name='Användarnamn')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='Lösenord')),
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('mac_address', models.CharField(blank=True, max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='EndpointStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'OFFLINE'), (10, 'ONLINE'), (20, 'IN_CALL')])),
                ('software_version', models.CharField(max_length=100)),
                ('software_release', models.DateField(null=True)),
                ('uptime', models.IntegerField(default=0)),
                ('ts_last_check', models.DateTimeField(null=True)),
                ('endpoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='endpoint.Endpoint')),
            ],
        ),
    ]
