# Generated by Django 2.1.5 on 2019-04-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0002_auto_20190424_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointFirmware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_model', models.CharField(max_length=200)),
                ('ts_created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='firmware')),
            ],
        ),
        migrations.AlterModelOptions(
            name='endpointbackup',
            options={'ordering': ('-ts_created',)},
        ),
        migrations.AddField(
            model_name='endpoint',
            name='manufacturer',
            field=models.SmallIntegerField(choices=[(0, 'OTHER'), (10, 'CISCO_CE'), (20, 'CISCO_CMS')], default=10),
            preserve_default=False,
        ),
    ]
