# Generated by Django 2.1.5 on 2019-04-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0003_auto_20190424_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpointfirmware',
            old_name='endpoint_model',
            new_name='model',
        ),
        migrations.AddField(
            model_name='endpointfirmware',
            name='manufacturer',
            field=models.SmallIntegerField(choices=[(0, 'OTHER'), (10, 'CISCO_CE'), (20, 'CISCO_CMS')], default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endpointfirmware',
            name='version',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
