# Generated by Django 2.1.5 on 2019-06-19 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0006_auto_20190619_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpointstatus',
            name='customer',
        ),
    ]
