# Generated by Django 2.1.5 on 2019-06-20 11:59

import django.db.models.deletion
from django.db import migrations, models

import endpoint.models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0015_auto_20190620_1105'),
        ('endpoint', '0009_auto_20190620_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointSIPAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sip', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='endpoint',
            name='meetings',
            field=models.ManyToManyField(blank=True, related_name='endpoints', through='endpoint.EndpointMeetingParticipant', to='provider.Meeting'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='email_key',
            field=models.CharField(blank=True, default=endpoint.models.default_key, max_length=200, verbose_name='E-postbrevlåda'),
        ),
        migrations.AlterField(
            model_name='endpointmeetingparticipant',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='endpoint.Endpoint'),
        ),
        migrations.AlterField(
            model_name='endpointmeetingparticipant',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='provider.Meeting'),
        ),
        migrations.AddField(
            model_name='endpointsipalias',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sip_aliases', to='endpoint.Endpoint'),
        ),
    ]
