# Generated by Django 2.1.5 on 2019-06-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0010_auto_20190620_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Namn'),
        ),
    ]
