# Generated by Django 2.1.5 on 2019-08-13 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpointproxy', '0001_initial'),
        ('endpoint', '0011_endpoint_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='endpointproxy.EndpointProxy'),
        ),
    ]
