# Generated by Django 2.1.5 on 2019-08-15 12:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0012_endpoint_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='has_warnings',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='ts_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
