# Generated by Django 2.1.5 on 2019-08-19 07:35

from django.db import migrations, models

import endpoint.consts


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0013_auto_20190815_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='sip_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='endpointstatus',
            name='status',
            field=models.SmallIntegerField(choices=[(-2, 'CONNECTION_ERROR'), (-1, 'AUTH_ERROR'), (0, 'OFFLINE'), (10, 'ONLINE'), (20, 'IN_CALL')], default=endpoint.consts.STATUS(-2)),
        ),
    ]
