# Generated by Django 2.1.5 on 2019-08-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0014_auto_20190819_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointstatus',
            name='ts_last_online',
            field=models.DateTimeField(null=True),
        ),
    ]
