# Generated by Django 2.1.5 on 2019-08-26 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20190110_1434'),
        ('endpoint', '0015_endpointstatus_ts_last_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.OrganizationUnit'),
        ),
    ]
