# Generated by Django 2.1.5 on 2019-09-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0016_endpoint_org_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='session_id',
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
    ]
