# Generated by Django 2.1.5 on 2019-09-06 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0017_merge_20190903_0934'),
        ('address', '0012_auto_20190904_1510'),
        ('endpoint', '0017_endpoint_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDefaultPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.SmallIntegerField(default=0, null=True)),
                ('password', models.CharField(max_length=100)),
                ('customer', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='provider.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time_before', models.IntegerField(default=5, verbose_name='Visa bokning före möte, antal minuter')),
                ('customer', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='provider.Customer')),
                ('default_address_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.AddressBook')),
            ],
        ),
    ]
