# Generated by Django 2.1.5 on 2019-09-06 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0018_customerdefaultpassword_customersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdefaultpassword',
            name='customer',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='provider.Customer'),
        ),
    ]
