# Generated by Django 2.1.5 on 2019-09-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0020_endpointfirmware_orig_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointbackup',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
