# Generated by Django 2.1.5 on 2019-09-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0024_auto_20190910_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointtask',
            name='backup',
            field=models.SmallIntegerField(null=True),
        ),
    ]
