# Generated by Django 2.1.5 on 2019-09-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0026_auto_20190911_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointtask',
            name='action',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
