# Generated by Django 2.1.5 on 2019-09-11 09:39

from django.db import migrations, models

import endpoint.consts


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0028_auto_20190911_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='connection_type',
            field=models.SmallIntegerField(choices=[(0, 'PASSIVE'), (1, 'DIRECT'), (2, 'PROXY')], default=endpoint.consts.CONNECTION(1)),
        ),
    ]
