# Generated by Django 2.1.5 on 2019-09-12 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0030_endpointtask_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointtask',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Customer'),
        ),
    ]
