# Generated by Django 2.1.5 on 2019-09-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0031_auto_20190912_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerdefaultpassword',
            options={'ordering': ('index',)},
        ),
        migrations.AlterModelOptions(
            name='endpointtask',
            options={'ordering': ('-ts_created',)},
        ),
        migrations.AddField(
            model_name='endpointtask',
            name='force_firmware',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='endpointtask',
            name='ts_last_attempt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
