# Generated by Django 2.1.5 on 2019-09-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0032_auto_20190912_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointtask',
            name='ts_last_attempt',
            field=models.DateTimeField(null=True),
        ),
    ]
