# Generated by Django 2.1.5 on 2019-09-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0034_customerautoregisteripnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersettings',
            name='use_standard_password',
            field=models.BooleanField(default=False, verbose_name='Försök skapa aktiv anslutning'),
        ),
    ]
