# Generated by Django 2.2.6 on 2019-11-14 17:00

from django.db import migrations, models

import endpoint.consts


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0035_customersettings_use_standard_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='connection_type',
            field=models.SmallIntegerField(choices=[(-10, 'INCOMING'), (0, 'PASSIVE'), (1, 'DIRECT'), (2, 'PROXY')], default=endpoint.consts.CONNECTION(1)),
        ),
    ]
