# Generated by Django 2.2.6 on 2019-12-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0036_auto_20191114_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersettings',
            name='dial_protocol',
            field=models.CharField(choices=[('SIP', 'SIP'), ('H323', 'H323'), ('H320', 'H320'), ('SPARK', 'SPARK')], default='SIP', max_length=100),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='dial_protocol',
            field=models.CharField(choices=[('', 'Standardinställning'), ('SIP', 'SIP'), ('H323', 'H323'), ('H320', 'H320'), ('SPARK', 'SPARK')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='session_id',
            field=models.CharField(blank=True, default='basic', editable=False, max_length=128),
        ),
    ]
