# Generated by Django 2.2.6 on 2019-12-06 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpointproxy', '0004_endpointproxy_is_online'),
        ('endpoint', '0037_auto_20191206_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersettings',
            name='default_proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='endpointproxy.EndpointProxy'),
        ),
    ]
