# Generated by Django 2.2.6 on 2020-01-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0038_customersettings_default_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='room_capacity',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Antal platser'),
        ),
    ]
