# Generated by Django 2.2.6 on 2020-01-08 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0039_endpoint_room_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointRoomPresence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('presence', models.BooleanField(default=False)),
                ('endpoint', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='endpoint.Endpoint')),
            ],
        ),
        migrations.CreateModel(
            name='EndpointHeadCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('count', models.SmallIntegerField(default=0)),
                ('endpoint', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='endpoint.Endpoint')),
            ],
        ),
    ]
