# Generated by Django 2.2.6 on 2020-01-23 14:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import compressed_store.models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0040_endpointheadcount_endpointroompresence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointheadcount',
            name='ts',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.localtime),
        ),
        migrations.CreateModel(
            name='EndpointDataContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('content_compressed', models.BinaryField()),
                ('extra_compressed', models.BinaryField(null=True)),
                ('content_type', models.SmallIntegerField(choices=[(0, 'configuration'), (1, 'status'), (2, 'macros'), (3, 'panels')])),
                ('hash', models.CharField(max_length=64)),
                ('endpoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='endpoint.Endpoint')),
            ],
            options={
                'abstract': False,
            },
            bases=(compressed_store.models.CompressedContentMixin, models.Model),
        ),
        migrations.AddField(
            model_name='endpointbackup',
            name='configuration',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='endpoint.EndpointDataContent'),
        ),
        migrations.AddField(
            model_name='endpointbackup',
            name='macros',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='endpoint.EndpointDataContent'),
        ),
        migrations.AddField(
            model_name='endpointbackup',
            name='panels',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='endpoint.EndpointDataContent'),
        ),
        migrations.AddField(
            model_name='endpointbackup',
            name='status',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='endpoint.EndpointDataContent'),
        ),
    ]
