# Generated by Django 2.2.6 on 2020-01-23 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0042_auto_20200123_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpointroompresence',
            name='endpoint',
        ),
        migrations.DeleteModel(
            name='EndpointHeadCount',
        ),
        migrations.DeleteModel(
            name='EndpointRoomPresence',
        ),
    ]
