# Generated by Django 2.2.6 on 2020-01-24 07:21

from django.db import migrations


def backward(apps, schema_editor):
    move_data(apps, schema_editor, reverse=True)


def move_data(apps, schema_editor, reverse=False):
    # NOTE: wont work with auto_now_add or many2manyfields

    from django.core.management.color import no_style
    from django.db import DEFAULT_DB_ALIAS, connections

    connection = connections[DEFAULT_DB_ALIAS]
    for m in ('EndpointBackup',):
        Model = apps.get_model('endpoint', m)
        Model2 = apps.get_model('endpoint_backup', m)

        if reverse:
            Model, Model2 = Model2, Model

        for m in Model2.objects.raw('SELECT * FROM {}'.format(Model._meta.db_table)):
            m.save(force_insert=True)

        statements = connection.ops.sequence_reset_sql(no_style(), [Model2])
        schema_editor.connection.cursor().execute('\n'.join(statements))


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0043_auto_20200123_2020'),
        ('endpoint_backup', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(move_data, reverse_code=backward),
        migrations.RemoveField(
            model_name='endpointdatacontent',
            name='endpoint',
        ),
        migrations.DeleteModel(
            name='EndpointBackup',
        ),
        migrations.DeleteModel(
            name='EndpointDataContent',
        ),
    ]
