# Generated by Django 2.2.6 on 2020-01-29 19:48

import django.db.models.deletion
from django.db import migrations, models

import endpoint.consts


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint_branding', '0002_auto_20200129_2048'),
        ('endpoint', '0044_auto_20200124_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersettings',
            name='default_branding_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='endpoint_branding.EndpointBrandingProfile'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='manufacturer',
            field=models.SmallIntegerField(choices=[(10, 'CISCO_CE')], default=endpoint.consts.MANUFACTURER(10)),
        ),
    ]
