# Generated by Django 2.2.6 on 2020-02-03 15:43

from django.db import migrations, models

import endpoint.consts


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0044_auto_20200124_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='manufacturer',
            field=models.SmallIntegerField(choices=[(10, 'CISCO_CE')], default=endpoint.consts.MANUFACTURER(10)),
        ),
    ]
