# Generated by Django 2.2.6 on 2020-02-04 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0045_auto_20200129_2048'),
        ('endpoint', '0046_customersettings_http_feedback_slot'),
    ]

    operations = [
    ]
