# Generated by Django 2.2.6 on 2020-02-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0047_merge_20200204_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='has_head_count',
            field=models.BooleanField(null=True),
        ),
    ]
