# Generated by Django 2.2.6 on 2020-02-14 13:04

from django.db import migrations, models

import endpoint.models


def set_ley(apps, schema):

    CustomerSettings = apps.get_model('endpoint.CustomerSettings')
    for s in CustomerSettings.objects.all():
        s.secret_key = endpoint.models.new_customer_secret()
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0048_endpoint_has_head_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersettings',
            name='secret_key',
            field=models.CharField(default=None, editable=False, max_length=100, null=True, unique=True, verbose_name='Nyckel'),
        ),
        migrations.RunPython(set_ley, lambda *args, **kwargs: True),
        migrations.AlterField(
            model_name='customersettings',
            name='secret_key',
            field=models.CharField(default=endpoint.models.new_customer_secret, editable=False, max_length=100, null=True, unique=True, verbose_name='Nyckel'),
        ),
    ]
