# Generated by Django 2.2.6 on 2020-02-19 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0049_customersettings_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointstatus',
            name='ts_last_event',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='endpointstatus',
            name='ts_last_provision',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='endpointstatus',
            name='ts_last_provision_document',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customersettings',
            name='customer',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='epm_settings', to='provider.Customer'),
        ),
    ]
