# Generated by Django 2.2.6 on 2020-04-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0050_auto_20200219_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='http_mode',
            field=models.SmallIntegerField(choices=[(0, 'HTTPS'), (10, 'HTTP')], default=0),
        ),
    ]
