# Generated by Django 2.2.12 on 2020-05-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0051_endpoint_http_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='ts_feedback_events_set',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
