# Generated by Django 2.2.12 on 2020-05-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0052_endpoint_ts_feedback_events_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersettings',
            name='night_first_hour',
            field=models.SmallIntegerField(default=23),
        ),
        migrations.AddField(
            model_name='customersettings',
            name='night_last_hour',
            field=models.SmallIntegerField(default=4),
        ),
    ]
