# Generated by Django 2.2.6 on 2020-09-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0052_auto_20200407_1115'),
        ('endpoint', '0054_auto_20200612_1629'),
    ]

    operations = [
    ]
