# Generated by Django 2.2.6 on 2020-11-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0056_auto_20201011_1718'),
    ]
    replaces = [
        ('endpoint', '0057_auto_20201104_1526'),
    ]
    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='webex_registration',
            field=models.BooleanField(null=True),
        ),
    ]
