# Generated by Django 2.2.6 on 2020-12-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0055_merge_20200921_1531'),
        ('endpoint', '0057_auto_20201106_1447'),
    ]
    replaces = [
        ('endpoint', '0058_auto_20201205_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='webex_registration',
        ),
    ]
