# Generated by Django 2.2.6 on 2020-12-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0057_auto_20201104_1526'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='webex_registration',
        ),

    ]
