# Generated by Django 2.2.6 on 2020-12-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0058_auto_20201205_1516'),
        ('endpoint', '0058_auto_20201205_1517'),
    ]

    operations = [
    ]
