# Generated by Django 2.2.6 on 2020-12-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0059_merge_20201205_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='webex_registration',
            field=models.BooleanField(null=True),
        ),
    ]
