# Generated by Django 2.2.6 on 2021-01-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0060_endpoint_webex_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointstatus',
            name='head_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='endpointstatus',
            name='presence',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='endpointstatus',
            name='ts_last_head_count',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='endpointstatus',
            name='ts_last_presence',
            field=models.DateTimeField(null=True),
        ),
    ]
