# Generated by Django 2.2.19 on 2021-03-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0061_auto_20210114_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointmeetingparticipant',
            name='head_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='endpointmeetingparticipant',
            name='presence',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='endpointmeetingparticipant',
            name='ts_connected',
            field=models.DateTimeField(null=True),
        ),
    ]
