# Generated by Django 2.2.19 on 2021-03-18 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0062_auto_20210316_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointstatus',
            name='active_meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='endpoint.EndpointMeetingParticipant'),
        ),
    ]
