# Generated by Django 2.2.24 on 2021-09-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0065_auto_20210616_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersettings',
            name='h323_gatekeeper',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customersettings',
            name='sip_proxy',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customersettings',
            name='sip_proxy_password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customersettings',
            name='sip_proxy_username',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
