# Generated by Django 2.2.24 on 2021-10-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0066_auto_20210928_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersettings',
            name='enable_obtp',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='customersettings',
            name='external_calendar_service',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
