# Generated by Django 2.2.24 on 2021-10-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0068_auto_20211008_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='owner_email_address',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endpoint',
            name='personal_system',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
