# Generated by Django 2.2.24 on 2021-11-05 09:21

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0070_auto_20211102_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, null=True),
        ),
    ]
