# Generated by Django 2.2.24 on 2021-11-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0071_auto_20211105_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='event_secret_key',
            field=models.CharField(default=None, max_length=64, null=True, unique=True),
        ),
    ]
