# Generated by Django 2.2.24 on 2021-11-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0072_auto_20211116_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersettings',
            name='proxy_password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
