# Generated by Django 2.2.24 on 2021-11-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0073_auto_20211121_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointstatus',
            name='ts_last_opened',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
