# Generated by Django 2.2.24 on 2021-11-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0074_auto_20211123_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersettings',
            old_name='external_calendar_service',
            new_name='external_manager_service',
        ),
    ]
