# Generated by Django 2.2.24 on 2021-11-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0075_auto_20211129_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='pexip_registration',
            field=models.BooleanField(null=True),
        ),
    ]
