# Generated by Django 2.2.24 on 2021-11-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0076_auto_20211129_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='external_manager_service',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
