# Generated by Django 2.2.24 on 2021-12-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0078_auto_20211202_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointmeetingparticipant',
            name='air_quality',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='endpointstatus',
            name='air_quality',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='endpointstatus',
            name='humidity',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='endpointstatus',
            name='temperature',
            field=models.SmallIntegerField(null=True),
        ),
    ]
