# Generated by Django 2.2.19 on 2021-03-25 16:07

from django.db import migrations, models
import django.db.models.deletion
import exchange.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0062_auto_20210325_1653'),
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256)),
                ('folder_id', models.CharField(max_length=256)),
                ('cached_name', models.CharField(max_length=100)),
                ('cached_path', models.CharField(default='', max_length=100)),
                ('autodiscover_data', exchange.fields.AutoDiscoverJSONField(default=dict, editable=False)),
                ('is_working', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('type', models.SmallIntegerField(default=0)),
                ('last_modified_time', models.DateTimeField(null=True)),
                ('last_incremental_sync', models.DateTimeField(null=True)),
                ('is_working', models.BooleanField(default=False)),
                ('video_meetings_only', models.BooleanField(default=True)),
                ('autodiscover_data', exchange.fields.AutoDiscoverJSONField(default=dict, editable=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=256)),
                ('changekey', models.CharField(max_length=256)),
                ('ical_uid', models.CharField(max_length=256)),
                ('calendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calendar_invite.Calendar')),
                ('credentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_invite.Credentials')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting')),
            ],
        ),
    ]
