# Generated by Django 2.2.19 on 2021-03-25 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endpoint', '0064_auto_20210325_1653'),
        ('calendar_invite', '0001_initial'),
        ('api_key', '0001_initial'),
        ('meeting', '0002_auto_20210325_1707'),
        ('provider', '0062_auto_20210325_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendaritem',
            name='recurring_meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meeting.RecurringMeeting'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='credentials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_invite.Credentials'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='customer',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.Customer'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='endpoint.Endpoint'),
        ),
        migrations.AlterUniqueTogether(
            name='calendaritem',
            unique_together={('credentials', 'item_id')},
        ),
        migrations.AlterUniqueTogether(
            name='calendar',
            unique_together={('endpoint', 'folder_id', 'username')},
        ),
        migrations.AddField(
            model_name='credentials',
            name='oauth_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_key.OAuthCredential'),
        ),
    ]
