# Generated by Django 2.2.19 on 2021-04-01 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_invite', '0003_auto_20210331_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='last_sync',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
