# Generated by Django 2.2.19 on 2021-04-01 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_invite', '0004_auto_20210401_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='last_sync_error',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
