# Generated by Django 2.2.19 on 2021-04-13 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_invite', '0005_auto_20210401_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='enable_sync',
            field=models.BooleanField(default=True),
        ),
    ]
