# Generated by Django 2.2.6 on 2020-06-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.FileField(blank=True, upload_to='theme', verbose_name='Logo')),
            ],
        ),
    ]
