# Generated by Django 2.2.6 on 2020-06-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='dark_mode',
            field=models.BooleanField(default=False, verbose_name='Använd mörk bakgrund där logotyp visas'),
        ),
    ]
