# Generated by Django 2.2.18 on 2021-02-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_auto_20200605_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='favicon',
            field=models.FileField(blank=True, upload_to='theme'),
        ),
    ]
