# Generated by Django 2.2.6 on 2020-09-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_rule', '0002_auto_20200918_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrule',
            name='match_source_mode',
            field=models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='AND', max_length=250),
        ),
    ]
