# Generated by Django 2.2.6 on 2020-09-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_rule', '0003_auto_20200918_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrule',
            name='sync_back',
            field=models.BooleanField(default=True, verbose_name='Sync back to Pexip'),
        ),
    ]
