# Generated by Django 2.2.6 on 2020-09-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_rule', '0004_auto_20200923_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrule',
            name='in_sync',
            field=models.BooleanField(default=False, editable=False, verbose_name='In sync'),
        ),
    ]
