# Generated by Django 2.2.6 on 2020-09-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_rule', '0006_auto_20200924_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrule',
            name='is_fallback',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
