# Generated by Django 2.2.6 on 2020-10-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_rule', '0007_auto_20200929_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrule',
            name='match_source_location_name',
            field=models.CharField(blank=True, editable=False, max_length=250),
        ),
    ]
