# Generated by Django 2.2.6 on 2020-10-14 13:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy_rule', '0008_auto_20201014_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyRuleHitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('count', models.IntegerField(default=1)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy_rule.PolicyRule')),
            ],
        ),
    ]
