# Generated by Django 2.2.26 on 2022-03-04 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('ts_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.TextField()),
            ],
        ),
    ]
